### ISSUE TITLE
Aanbevolen eigenschappen van een begrip

### ISSUE THREAD

**Issue by FinnTiebout** [pldn/nederlands-profiel-voor-stelselcatalogi#10]
Naast de verplichte eigenschappen van een begrip kennen we ook aanbevolen eigenschappen welke wij vanuit het profiel adviseren te gebruiken. 
Wat zijn de aanbevolen eigenschappen vanuit ons profiel?

**Comment by lvdbrink** [comment]
Mijn kandidaten: 
- Mensvriendelijke definitie > ik stel voor om deze 'Toelichting' te noemen. We spraken erover dat dit eigenlijk geen definitie is; een begrip heeft maar één echte definitie. Deze mensvriendelijke variant is eigenlijk een uitleg van de definitie voor leken, een toelichting dus. 
- hierarchische relaties
- verwantschapsrelaties (equivalent etc)

**Comment by FinnTiebout** [comment]
Mijn voorstel:

een gebruiksvriendelijke toelichting hebben als aanvulling op de definitie.
één of meerdere alternatieven termen hebben.
één of meerdere alternatieve schrijfwijzen (ook typefouten) hebben.
één of meerdere zoektermen en/of trefwoorden hebben.
kan hetzelfde zijn als één of meer andere begrippen.
kan ongeveer hetzelfde zijn als één of meer andere begrippen.
kan bestaan uit één of meer andere begrippen.
kan een verbijzondering zijn van één of meer ander begrippen.

**Comment by lvdbrink** [comment]
> één of meerdere alternatieven termen hebben.
één of meerdere alternatieve schrijfwijzen (ook typefouten) hebben.
één of meerdere zoektermen en/of trefwoorden hebben.

Waarom deze als aanbevolen? Ik zou ze als optioneel opnemen. Je kan prima een term hebben (bijvoorbeeld, ik noem maar wat, 'akkerbouw'), dat één helder label heeft, en geen alternatieven. Dan zou het gekunsteld worden om daar alternatieven of trefwoorden voor te gaan bedenken. 

> kan bestaan uit één of meer andere begrippen.
Wat bedoel je daarmee, dat een begrip kan bestaan uit andere begrippen?

**Comment by pmaria** [comment]
> één of meerdere alternatieve schrijfwijzen (ook typefouten) hebben.
> één of meerdere alternatieve schrijfwijzen (ook typefouten) hebben.

Dit zou ik optioneel opnemen.

> kan hetzelfde zijn als één of meer andere begrippen.

In een andere context neem ik aan. Of dit nuttig is hangt af van de situatie. Ik zou dit optioneel houden.

> kan ongeveer hetzelfde zijn als één of meer andere begrippen.

Wederom neem ik hier aan dat het om begrippen in een andere context gaat. Ook dit zou ik optioneel houden.

> kan bestaan uit één of meer andere begrippen.

Heb je voorbeelden van een nuttige toepassing van deze relatie?

**Comment by GeraldGrootRoessink** [comment]
Het zit niet in SKOS maar omdat we allemaal overheid  zijn, stel ook voor:
- wettelijke grondslag.

**Comment by FinnTiebout** [comment]
samenvatting o.b.v. opmerkingen Pano en Linda:
Deze eigenschappen worden _optioneel_, _aanbevolen_ zou gebruikers te veel 'dwingen' om deze te vullen, hierdoor ontstaat geknutsel.

- één of meerdere alternatieven termen hebben. 
- één of meerdere alternatieve schrijfwijzen (ook typefouten) hebben. 
- één of meerdere zoektermen en/of trefwoorden hebben.
- kan hetzelfde zijn als één of meer andere begrippen.
- kan ongeveer hetzelfde zijn als één of meer andere begrippen.

**Comment by FinnTiebout** [comment]
reactie op vraag Pano en Linda omtrend de relatie _kan bestaan uit één of meer andere begrippen._

Ik denk hierbij aan een fiets, welke uit een frame en wielen bestaat. Frame en Wiel zijn dan gerelateerde begrippen.

**Comment by pmaria** [comment]
Tegenvraag: Stel dat je in je thesaurus naast `fiets` ook de concepten `voertuig` en `auto` hebt, die ook wielen kunnen hebben. Misschien wil je ook onderscheid maken tussen autowielen en fietswielen. Hoe zou je deze concepten dan organiseren?

**Comment by FinnTiebout** [comment]
Afhankelijk van het doel en de granulariteit van je thesaurus. 
1. een fiets bestaat uit wielen
2. een auto bestaat uit wielen
Maar nu ik dit zo opschrijf, betwijfel ik of het wel semantische relaties zijn.

**Comment by FinnTiebout** [comment]
Conclusie:

Optionele eigenschappen; dit zijn eigenschappen die we herkenen binnen het profiel, ze zijn niet verplicht. 
Aanbevolen eigenschappen: dit zijn optionele eigenschappen waarvan wij als werkgroep zeggen dat het als nuttig wordt ervaren deze mee te geven. 

Optionele eigenschappen:
Een begrip kan één of meerdere alternatieven termen hebben.
Een begrip kan één of meerdere alternatieve schrijfwijzen (ook typefouten) hebben.
Een begrip kan één of meerdere zoektermen en/of trefwoorden hebben.
Een begrip kan hetzelfde zijn als een ander begrip.
Een begrip kan ongeveer hetzelfde zijn als een ander begrip.
Een begrip kan een verbijzondering zijn van een ander begrip

Aanbevolen eigenschappen:
Een begrip kan een gebruiksvriendelijke toelichting hebben als aanvulling op de definitie.

**Comment by pmaria** [comment]
Mijn punt is dat het niet gemakkelijk is om verschillende soorten hiërarchische relaties te vermengen in 1 thesaurus.

```yaml
begrippen:
  - term: voertuig
    specialisatie:
      - term: auto
        bestaatUit:
          - term: autowiel
            specialisatie:
              - term: fietswiel
      - term: fiets
        bestaatUit:
          - term: fietswiel
    bestaatUit:
      - term: wiel
        specialisatie: 
          - term: autowiel
            specialisatie:
              - term: fietswiel
```
In bovenstaand voorbeeld heb ik expres overal begrippen herhaalt, maar je ziet dat je in je hiërarchie een ordeningsprobleem krijgt.

Daarnaast heb ik persoonlijk nog nooit echt behoefte gehad voor een organisatie langs deel/geheel relaties in een thesaurus. Bij deel/geheel relaties gaat het m.i. meestal over exemplaren/instanties/dingen die bestaan uit andere exemplaren en niet om (referentie)concepten die bestaan uit andere (referentie)concepten. 

Hoewel, ik kan me voorstellen dat dat laatste in bepaalde situaties interessant is. Bijv. in de medische wereld waarin je een opdeling van lichaamsdelen als referentieconcepten wilt hebben o.i.d. Maar dit is een wat uitzonderlijke toepassing die ik buiten beschouwing zou laten voor dit profiel.
Mocht er toch een goede reden zijn om dit op te nemen (ik laat me graag overtuigen), dan moeten er duidelijke richtlijnen komen voor het toepassen daarvan.

**Comment by KoosBoersma** [comment]
Zie ook discussie over isPartOf relatie. We moeten bepalen waarvoor we welke relatie gebruiken en welke relaties we in dit profiel vinden passen. Risico is dat we een ontologie aan het bouwen zijn. (overigens niet verkeerd want moet ook nog en zou goed zijn dat het aansluit)

**Comment by FinnTiebout** [comment]
Dit issue is erg algemeen, details worden in losse issues uitgewerkt. 
Dit issue kan dicht.
