### ISSUE TITLE
Optionele eigenschappen voor een begrip

### ISSUE THREAD

**Issue by FinnTiebout** [pldn/nederlands-profiel-voor-stelselcatalogi#11]
Welke optionele eigenschappen kennen wij vanuit het profiel voor een begrip.

Dit zijn eigenschappen welke niet perse aanbevolen zijn.

**Comment by lvdbrink** [comment]
Mijn kandidaten: 
    - alternatieve term
    - bron / herkomst
    - behoort tot groep (collecties)
    - redactionele notitie

**Comment by GeraldGrootRoessink** [comment]
Hier denk ik aan.
- voorbeelden
- engelstalige labels/notes
-

**Comment by FinnTiebout** [comment]
Conclusie:

**Optionele eigenschappen:**
Lexicale labels:

- Een begrip kan één of meerdere alternatieven termen hebben.
- Een begrip kan één of meerdere alternatieve schrijfwijzen (ook typefouten) hebben.
- Een begrip kan één of meerdere zoektermen en/of trefwoorden hebben.

Notations:
?

Documentatie eigenschappen:

- Een begrip kan een redactionele (editorial) notitie hebben
- Een begrip kan één of meerdere voorbeelden hebben

Semantische relaties:

- Een begrip kan hetzelfde zijn als een ander begrip.
- Een begrip kan ongeveer hetzelfde zijn als een ander begrip.
- Een begrip kan een verbijzondering zijn van een ander begrip

Niet Semantische relaties:

- Een begrip kan tot een bepaalde verzameling (collectie) behoren

Niet skos relaties:

- Een begrip kan een bronverwijzing hebben

**Comment by FinnTiebout** [comment]
_Een begrip kan een verbijzondering zijn van een ander begrip_ = _is specialisatie van_

**Comment by FinnTiebout** [comment]
@FinnTiebout werkt het verschil tussen verplicht en optioneel uit voor zover dat nog niet gedaan is. 
Daarna kan dit issue gesloten worden.

**Comment by ArjenSantema** [comment]
Opgenomen in Respec tekst
