### ISSUE TITLE
Wat verstaan we onder de verschillende type eigenschappen?

### ISSUE THREAD

**Issue by FinnTiebout** [pldn/nederlands-profiel-voor-stelselcatalogi#12]
We kennen de volgende type eigenschappen bij een begrip:

- verplicht
- aanbevolen
- optioneel.
Binnen dit issue deze type eigenschappen uitwerken.

**Comment by keestrautwein** [comment]
Uitgangspunt: Ik denk dat het belangrijk is om de lijst verplichte eigenschappen klein te houden:
1. Omdat in de praktijk veel partijen slechts een beperkt aantal eigenschappen voor ieder begrip gedefinieerd hebben. 
2. Omdat we alleen strikt noodzakelijke en door iedereen gedeelde eigenschappen overheidsbreed verplicht willen maken. 

Een catalogus kan zijn eigen verplichte eigenschappen invoeren (denk bijvoorbeeld aan geo-data) die dan landelijk als aanbevolen of optioneel gelden. 
Eigenschappen die we graag toegevoegd zouden zien maar die niet altijd aanwezig of relevant  zijn, zouden in de lijst "Aanbevolen eigenschappen" opgenomen moeten worden.

**Comment by lvdbrink** [comment]
> Uitgangspunt: Ik denk dat het belangrijk is om de lijst verplichte eigenschappen klein te houden

Eens. Ik had tijdens het overleg gisteren het gevoel dat we over dit uitgangspunt wel consensus hebben.

> Een catalogus kan zijn eigen verplichte eigenschappen invoeren (denk bijvoorbeeld aan geo-data)

Ik geef toe dat 'spatial is special', maar in het geval van begrippen definiëren heb ik niet het idee dat we behoefte aan speciale geo-eigenschappen hebben. 

Verplicht: Dit zijn eigenschappen die je verplicht moet toepassen om aan het NL SKOS profiel (of hoe we het ook gaan noemen) te voldoen. 
- Voorkeursterm
- Definitie
- (Context): hier hadden we discussie over. Het lijkt mij dat het begrippenkader waar het begrip in zit de context is, en dat je deze dus niet aan elk begrip hoeft toe te voegen. Ik zou deze niet verplicht stellen. 

Aanbevolen: Dit zijn eigenschappen die niet in elk geval nodig zijn, maar wel sterk door ons worden aangeraden. 
- Mensvriendelijke definitie > ik stel voor om deze 'Toelichting' te noemen. We spraken erover dat dit eigenlijk geen definitie is; een begrip heeft maar één echte definitie. Deze mensvriendelijke variant is eigenlijk een uitleg van de definitie voor leken, een toelichting dus. 
- Mijn andere kandidaten: 
    - hierarchische relaties
    - verwantschapsrelaties (equivalent etc)


Optioneel: Dit zijn eigenschappen die je ook kunt toepassen, en waarvan in het profiel afspraken zijn vastgelegd over toepassing en gebruik.
- Mijn kandidaten: 
    - alternatieve term
    - bron / herkomst
    - behoort tot groep (collecties)
    - redactionele notitie

Misschien kom ik nog met meer, ik ben nog niet helemaal klaar met mijn inventarisatie.

**Comment by lvdbrink** [comment]
Aanvullende opmerking: ik stel voor om ook in het NL profiel de opmerking op te nemen dat het is toegestaan om in je eigen begrippenkader bij begrippen eigenschappen op te nemen die helemaal niet in het NL profiel staan. De meerwaarde van optionele eigenschappen is dat er wel afspraken over zijn vastgelegd, wat interoperabiliteit bevordert.

**Comment by FinnTiebout** [comment]
> Aanvullende opmerking: ik stel voor om ook in het NL profiel de opmerking op te nemen dat het is toegestaan om in je eigen begrippenkader bij begrippen eigenschappen op te nemen die helemaal niet in het NL profiel staan. De meerwaarde van optionele eigenschappen is dat er wel afspraken over zijn vastgelegd, wat interoperabiliteit bevordert.

Eens, maar die eigenschappen gaan dan niet mee in de _uitwisseling_ naar een ander systeem.

**Comment by lvdbrink** [comment]
Ja, eens. Goed om dat expliciet te maken.

**Comment by FinnTiebout** [comment]
zie issue 11
@FinnTiebout

**Comment by ArjenSantema** [comment]
Opgenomen in Respec tekst

**Comment by ArjenSantema** [comment]
nog even uitzoeken hoe precies in profiel opnemen.

**Comment by ArjenSantema** [comment]
Dit kan heel mooi met SHACL , namelijk met behulp van sh:minCount in combinatie met sh:severity (dat de waarden sh:Info, sh:Warning en sh:Violation kan hebben) en als aanvulling sh:message.

Verplichte eigenschappen kunnen een sh:minCount van 1 krijgen in combinatie met een sh:Violation
Optionele eigenschappen kunnen een sh:minCount van 1 krijgen in combinatie met een sh:Warning

Mijn voorstel is om alleen de voorkeursterm verplicht te maken.

Niet altijd wordt een formele definitie gegeven. Zo definieert het Burgerlijk Wetboek in hoofdstuk 2 niet wat een rechtspersoon is. Dat is een juridisch gangbaar gebruik om de wet niet bij voorbaat onnodig in te perken. In zo'n geval kun je wel een uitleg geven. In het profiel heeft de definitie dan een sh:minCount van 1 en een sh:Severity met de waarde sh:Warning.
Voor die sh:Warning kunnen we dan een sh:Message in het profiel opnemen met in dit voorbeeld iets als 'Waar mogelijk wordt een definitie van een concept gegeven, maar als er geen formele definitie beschikbaar is wordt altijd een uitleg gegeven'. 
Hiermee is nog geen waterdichte validatie mogelijk, maar het geeft wel duidelijk aan hoe het profiel kan worden gebruikt.

**Comment by architolk** [comment]
Arjen verwerkt dit conform voorstel

**Comment by ArjenSantema** [comment]
is uitgewerkt en voldoende beschreven
