### ISSUE TITLE
4 niveau's van Catalogi/begrippenkaders

### ISSUE THREAD

**Issue by FinnTiebout** [pldn/nederlands-profiel-voor-stelselcatalogi#14]
Toelichten dat het altijd over concepten gaat en niet over andere 'dingen'.

Binnen een ontologie kunnen we ook andere zaken beschrijven. Dat laten we voorlopig even buiten beschouwing.

**Comment by FinnTiebout** [comment]
1. Begrippenlijsten: begrippen binnen een gegeven domein kenbaar maken, geen onderlinge relaties, wel definities.
2. Taxonomie: begrippenlijsten met als aanvulling de onderlinge hierarchische relaties tussen begrippen.
3. Thesaurus: een Taxonomie met als aanvulling eenvoudige niet hierarchische relaties. 
4. Thesaurus met extra semantiek, Samenhangend stelsel waarover geredeneerd kan worden met ‘specifieke’ relaties.

**Comment by pmaria** [comment]
> 4. Thesaurus met extra semantiek, Samenhangend stelsel waarover geredeneerd kan worden met ‘specifieke’ relaties.

 Wat is de use case hiervoor? Wanneer wil je meer semantiek vastleggen over begrippen dan een "normale" thesaurus?
