### ISSUE TITLE
skos:related vs skos:semanticRelation

### ISSUE THREAD

**Issue by FinnTiebout** [pldn/nederlands-profiel-voor-stelselcatalogi#17]
Best practice opstellen:
Wat is het onderscheid tussen skos:related en skos:semanticRelation, wanneer gebruik je welke eigenschap?

**Comment by pmaria** [comment]
`skos:semanticRelation` is een abstracte eigenschap. Het is namelijk de super-property van:
* `skos:related`
* `skos:broaderTransitive`
    * `skos:broader` 
*  `skos:narrowerTransitive`
    * `skos:narrower`

Zie ook deze note uit de skos ontologie zelf:
```
This property should not be used directly, but as a super-property for all properties denoting a relationship of meaning between concepts.
```

Deze eigenschap moet dus niet direct gebruikt worden.

**Comment by ArjenSantema** [comment]
Met opmerking hierboven sluiten. Skos:semanticRelation dus niet gebruiken  in skos profiel.
