### ISSUE TITLE
URI patroon voor begrippen (en mogelijk andere resources)

### ISSUE THREAD

**Issue by FinnTiebout** [pldn/nederlands-profiel-voor-stelselcatalogi#18]
n.a.v. issue https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/issues/1  

Hoe moet het URI patroon (de URI strategie) er voor begrippen uitzien?
- moet de term opgenomen worden in de URI?
- werken we met een mensleesbare URI?
- werken we met een URI met GUID's?
- komen er andere zaken uit het informatiemodel/KOS model terug in de URI strategie?
- - denk aan het conceptschema, domein of de collection zoals we dat bij de DSO doen.

**Comment by keestrautwein** [comment]
Kunnen we URI strategie niet laten aan de partij die de URI's maakt? 
Anders maken we de URI strategie onderdeel van dit profiel. Lijkt me te complex daar voor.

**Comment by ArjenSantema** [comment]
Uri strategie is geen onderwerp van deze werkgroep.
Ieder begrip heeft een persistente uri, meer zeggen we hier niet over.
