### ISSUE TITLE
Nederlands talige beschrijving externe semantische relaties

### ISSUE THREAD

**Issue by FinnTiebout** [pldn/nederlands-profiel-voor-stelselcatalogi#19]
in issue https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/issues/5 is besloten welke externe semantische relaties we kunnen leggen. 

Binne dit issue graag de betreffende paragraaf bijwerken. 
https://pldn.github.io/nederlands-profiel-voor-stelselcatalogi/#externe-semantische-relaties

1. Nederlands talige labels voor de vier eigenschappen.
2. Nederlands talige uitleg van het gebruik van de properties.

**Comment by ArjenSantema** [comment]
@FinnTiebout

**Comment by ArjenSantema** [comment]
Opgenomen in Respec Tekst.
