### ISSUE TITLE
Thesaurus - gebruik overige labels

### ISSUE THREAD

**Issue by ArjenSantema** [pldn/nederlands-profiel-voor-stelselcatalogi#2]
Stelling:

1. good practice: gebruik het altLabel voor 'echte' synoniemen.
2. good practice: gebruik hiddenLabel voor termen die niet echt synoniem zijn, maar die wel naar het concept leiden als hierop wordt gezocht. 
3. good practice: monitor je zoekscherm en voeg de (nieuwe) termen waar op wordt gezocht als hidden label aan het concept waar de gebruiker uiteindelijk uit komt (dit vraag nog wel wat operationalisatie).

**Comment by kad-stapr** [comment]
Bij veel van de type labels is er behoefte aan het gebruik van language tags om de link tussen het concept en verschillende natuurlijke talen te leggen. Het is goed om een good practice te definiëren waarin we vastleggen of we een concept via een prefLabel in meerder natuurlijke talen willen kunnen uitdrukken, of dat we een keuze maken waarbij we het concept en het label/term ontkoppelen en de mogelijkheid ontstaat om vanuit een concept te refereren naar een andere label/term-resource. Nadeel van deze optie is dat het model complexer wordt, maar met het definiëren van goede guidelines zou de complexiteit gereduceerd kunnen worden.
_Voorbeeld_: eigendom@nl en property@en zijn Label/Term die naar verschillende concepten verwijzen, maar via bv een skosxl:altLabel naar elkaar kunnen verwijzen. Verwijzing is dan niet naar één gelijk concept maar naar resp. een Engels en Nederlands concept.....

**Comment by GeraldGrootRoessink** [comment]
Stel me voor dat we, bijvoorbeeld,  universiteiten in Nederland willen aanbieden aan EU-burger om daarop te kunnen inschrijven. Hoe mooi zou het zijn als de taalvoorkeur van die persoon opgegeven in de applicatie automatisch filtert op het goede taallabel. IK denk dat het kan, maar weet eerlijk gezegd niet hoe.

**Comment by FinnTiebout** [comment]
Conclusie:
1. Synoniem= een ander label/term voor hetzelfde binnen de gegeven context. We gebruiken hiervoor altLabel.
2. hiddenLabel --> een lexicaal label voor een bron, waarbij een KOS-ontwerper zou willen dat die tekenreeks toegankelijk is voor toepassingen die op tekst gebaseerde indexerings- en zoekbewerkingen uitvoeren, maar niet zou willen dat label anders zichtbaar is. Verborgen labels kunnen bijvoorbeeld worden gebruikt om verkeerd gespelde varianten van andere lexicale labels op te nemen.
3. monitor je zoekscherm --> Dit is een vooral een algemene goodpractice te implementeren bij de applicatie/toepassing.
