### ISSUE TITLE
Gebruik van Bronverwijzingen

### ISSUE THREAD

**Issue by FinnTiebout** [pldn/nederlands-profiel-voor-stelselcatalogi#20]
Hoe gaan we binnen het profiel om met bronverwijzingen?
Welke type bronnen kennen we?
- digitale bronnen
- analoge bronnen
- de echte wereld, de natuurlijk taal, de werkelijkheid.
- ?

**Comment by pietervaneverdingen** [comment]
Bij bronnen zou ik ook onderscheid willen maken tussen:
- wettelijke bronnen en niet-wettelijke bronnen
- bronorganisaties waar je naar wilt verwijzen (al dan niet met contactgegevens), maar die vallen meer onder master data

**Comment by ArjenSantema** [comment]
Wij willen bij voorkeur verwijzen naar een bron die vindbaar is op het web, bijvoorbeeld met de permanente link volgens de linktool van wetten.nl. Maar als er geen digitale bron is, maar bijvoorbeeld een (nog niet gedigitaliseerd) boek, dan moet je naar een document verwijzen.
De verwijzing naar een bronorganisatie zou ik onder provenance vatten, maar dat is een ander onderwerp.

**Comment by keestrautwein** [comment]
_Voorstel voor tekst van best practise:_

### Standaard gebruik dct:source
Bronnen kunnen worden aangegeven met behulp van dct:source, waarin op twee manieren naar (vaak externe) bron verwezen kan worden. Ten eerste kan deze eigenschap een een URL of URI bevatten die verwijst naar de bron op het internet. Als niet naar de bron verwezen kan worden kan er een beschrijving van de grond opgenomen in een string. Dit is bijvoorbeeld het geval als we willen verwijzen naar fysieke object zonder URL/URI representatie maar ook digitale objecten zonder identificerend kenmerk kunnen hieronder vallen

### Gebreken standaard oplossing
 Er zijn drie problemen met de standaard oplossing: 

1. Systemen die de dct:source eigenschap willen verwerken, moeten zelf afleiden of de waarde ervan een URL of een string is. Dit is geen triviaal onderscheid en leidt tot complexe code in het ontvangende systeem;
2. Als er de bron beschreven moet worden is daarvoor geen standaard. Alle informatie moet in een string worden beschreven, waardoor machinale verwerking van de string moeilijk is. De string kan vaak alleen door een menselijke eindgebruiker geïnterpreteerd worden;   
3. Als er extra informatie over de bron opgeslagen moet worden, is daar geen standaard oplossing voor. Die informatie kan opgenomen worden in de string, maar dat heeft dezelfde nadelen als onder punt 2 hierboven.

### Best practise oplossing
Om vanuit object A in catalogus C naar een bron B te verwijzen stellen we de volgende best practise uitgangspunten voor: 

1. We vullen dct:source in object A alleen met een URI's of URL's. Er wordt nooit een string gebruikt omdat dit voor problemen zorgt bij de consumerende systemen van deze informatie;
2. Als bron B adresseerbaar is met een URL of URI en er verder geen gegevens over de bron opgeslagen hoeven te worden, voldoet de standaard toepassing van dct:source. Object A gebruikt dan eigenschap dct:source met daarin de URL om direct naar bron B te verwijzen. ;
3. Als bron B niet addresseerbaar is met een URL (of URI) wordt in catalogus C een extra verwijsobject V aangemaakt met een eigen URI. In A wordt met dct:source verwezen naar dit verwijsobject V. In verwijsobject V wordt met behulp van eigenschappen de informatie vastgelegd waarmee bron B beschreven kan worden;
4. Ook als bron B een URL heeft, maar het is noodzakelijk om meer informatie vast te leggen over deze bron, wordt er een verwijsobject V aangemaakt waarnaar object A verwijst m.b.v. de URI in eigenschap dct:source. Deze extra informatie wordt opgenomen in V. In verwijsobject V wordt naast de andere eigenschappen ook dct:source gebruikt om met de URL naar object B te verwijzen. 

Merk op dat als bron B in hetzelfde systeem bestaat als object A de situatie onder punt 3 niet van toepassing zou moeten zijn. In een goed ontworpen catalogus C, zal bron B altijd adresseerbaar zijn met een URI.

### Over het verwijsobject
We kunnen een aantal eigenschappen van het verwijsobject beschrijven. Het is moeilijk om een duidelijk verwijzing naar een object uit de fysieke wereld vast te leggen omdat daarin logischerwijs extreem veel variëteit bestaat en ook sterk afhangt van de context waarin verwezen wordt. We sluiten daarom aan bij de oplossing van dct:source. Een verwijsobject bevat ten minste de volgende eigenschappen:

1. Een optioneel dct:source veld met daarin een verwijzing naar het bronobject B. Dit veld wordt altijd gevuld met de URL of URI van bron B als die adresseerbaar is. Dit veld blijft altijd leeg als B niet met een URL adresseerbaar is;
2. Een optionele bron-beschrijving waarin een een tekstuele beschrijving is opgenomen van bron B als die niet met een Url geïdentificeerd kan worden. Dit veld wordt niet ingevuld als de bron een URL/URI heeft;
3. Optioneel een gebruikerstekst. Deze string kan getoond worden aan gebruikers om bron B te beschrijven. Deze gebruikerstekst wordt met name getoond in een gebruikersinterface;
4. Optioneel andere gebruikelijke velden zoals labels en toelichtingen. Een definitie lijkt voor verwijsobjecten niet voor de hand te liggen.

Verder kan het verwijsobject naar believen worden uitgebreid, bijvoorbeeld met:

- Geo-informatie of andere coordinaten om de locatie van een fysiek object op te slaan;
- Een identificerend kenmerk dat buiten het Linked Data domein bestaat, zoals in een magazijn o.i.d;
- Een waarde waarmee bronnen kunnen worden gecategoriseerd;
- Provenance en andere metainformatie over de bron.

Merk op dat provenance informatie over de bron anders opgeslagen wordt dan de provenance informatie van de objecten in catalogus C zelf. We verwijzen naar de uitleg elders om de provenance informatie vast te leggen van de objecten in catalogus C, zoals die van object A en van verwijsobject V zelf.

**Comment by keestrautwein** [comment]
Een diagrammetje erbij zou veel verduidelijken, maar dat is hier wat lastig in te voeren.

**Comment by ArjenSantema** [comment]
Wij hebben een oplossing die hier erg op lijkt, maar niet een verwijsobject als 'tussen-resource' nodig heeft zoals optie 4 hierboven. Bij het concept gebruiken wij dct:source om te verwijzen naar een persistente uri van de bron, bijvoorbeeld:

* kad:Perceel dct:source <https://wetten.overheid.nl/jci1.3:c:BWBR0004541&hoofdstuk=1&artikel=1>. (conform de linktool van wetten.nl)
* <https://wetten.overheid.nl/jci1.3:c:BWBR0005288&boek=5&titeldeel=1&artikel=1> rdfs:label "artikel 1 Burgerlijk Wetboek Boek 5"@nl. (met als label de citeertitel conform de linktool van wetten.nl; het zou aardig zijn als wetten.nl dit zelf op deze wijze zou ontsluiten). 
* Naast de citeertitel kun je ook bijvoorbeeld provenance informatie toevoegen aan deze resource.
 
Als je niet naar een resource op het web verwijst (optie 3 hierboven) moet je dan wel een verwijsobject creëren om altijd bij een resolvebare bron uit te komen.

**Comment by ArjenSantema** [comment]
Er zit nog wel een verborgen tweede practice in deze wijze van verwijzing naar de bron in de wet. Wij hebben de zichtdatum uit de link gesloopt. Daarmee verwijzen we naar artikel 1 in het algemeen, ofwel alle versies van artikel 1 die er ooit geweest zijn of nog gaan komen. Dat past bij de gedachte dat het concept ook het 'algemene' concept is (hier https://tax.kadaster.nl/id/concept/Perceel), dat op zich natuurlijk wel verschillende beschrijvingen kan hebben (https://tax.kadaster.nl/doc/concept/Perceel). Bij de versie van de beschrijving kunnen we provenance data opnemen.

**Comment by keestrautwein** [comment]
Omdat we in de overheid vaak verwijzen naar de wetten, lijkt het nuttig aan dat bijzondere, "verborgen", geval een paar woorden te wijden. Over versionering (van wetten) is veel te zeggen, maar ik kan met wel vinden dat je in een concept zelden verwijst naar een specifieke versie van een wet, maar naar de wet zelf. Inhoudelijk bedoel je waarschijnlijk wel de meeste recente versie van de wet. Als een nieuwe versie van een wet het bestaan van een begrip niet langer vereist, zou je het begrip moeten verwijderen. (wat op zich een complex proces kan zijn waarbij ik me kan voorstellen dat je (tijdelijk) wel naar een versie van een wet gaat verwijzen)

**Comment by keestrautwein** [comment]
> * provenance

**Comment by keestrautwein** [comment]
> Wij hebben een oplossing die hier erg op lijkt, maar niet een verwijsobject als 'tussen-resource' nodig heeft zoals optie 4 hierboven. Bij het concept gebruiken wij dct:source om te verwijzen naar een persistente uri van de bron, bijvoorbeeld:
> 
> * kad:Perceel dct:source https://wetten.overheid.nl/jci1.3:c:BWBR0004541&hoofdstuk=1&artikel=1. (conform de linktool van wetten.nl)
> * https://wetten.overheid.nl/jci1.3:c:BWBR0005288&boek=5&titeldeel=1&artikel=1 rdfs:label "artikel 1 Burgerlijk Wetboek Boek 5"@nl. (met als label de citeertitel conform de linktool van wetten.nl; het zou aardig zijn als wetten.nl dit zelf op deze wijze zou ontsluiten).
> * Naast de citeertitel kun je ook bijvoorbeeld provenance informatie toevoegen aan deze resource.
> 
> Als je niet naar een resource op het web verwijst (optie 3 hierboven) moet je dan wel een verwijsobject creëren om altijd bij een resolvebare bron uit te komen.

Ik begrijp de oplossing die Arjen hier beschrijft voor optie onder punt 3 niet helemaal. Voeg je extra properties aan object A (kad:Perceel) toe? T.w. de URI met dct:source en een extra label voor de externe bron?
Als de bron meerdere keren gebruikt wordt, lijkt dat redundantie in de hand te werken. Of begrip ik het niet?

**Comment by ArjenSantema** [comment]
Ik bedoel dat je naast de citeertiteel bijvoorbeeld ook de zichtdatum als leesbaar gegeven (dus als datum) kunt tonen.

**Comment by pmaria** [comment]
Ik denk zelf aan zoiets. 

[![](https://mermaid.ink/img/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gICAgQ29uY2VwdCAtLT4gXCIwLi4qXCIgQnJvbjogYnJvblxuICAgIEJyb24gLS0-IFwiMC4uMVwiIFJlc291cmNlOiB1cmxcblxuICAgIGNsYXNzIEJyb24ge1xuICAgICAgICBuYWFtOiBTdHJpbmdcbiAgICAgICAgYmVzY2hyaWp2aW5nOiBTdHJpbmcgWzAuLjFdXG4gICAgfSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)](https://mermaid.live/edit#eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gICAgQ29uY2VwdCAtLT4gXCIwLi4qXCIgQnJvbjogYnJvblxuICAgIEJyb24gLS0-IFwiMC4uMVwiIFJlc291cmNlOiB1cmxcblxuICAgIGNsYXNzIEJyb24ge1xuICAgICAgICBuYWFtOiBTdHJpbmdcbiAgICAgICAgYmVzY2hyaWp2aW5nOiBTdHJpbmcgWzAuLjFdXG4gICAgfSIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9)

Volgens mij past dat op beide beschrijvingen

**Comment by KoosBoersma** [comment]
Als ik de beschrijving volg dan hebben we meerdere labels aangezien er een gelaagdheid gemaakt is. 

Een concept heeft een bron (welk label gaan we hier aan toekennen) en een bron heeft een resource verwijzing (label dct:source)

**Comment by FinnTiebout** [comment]
@architolk komt met een voorbeeld rondom oa:Annotation
open annotation is de standaard.

**Comment by ArjenSantema** [comment]
Wordt vóór 31/3 uitgewerkt door @KoosBoersma, @keestrautwein , @hansoverbeek en @pmaria

**Comment by RiX012** [comment]
Mijn (simpele) voorstel zou zijn:

- **skos:Concept**
  - dc:source
    - **dc:Text**
      - _rdfs:label_, _dc:title_
      - _rdfs:comment_, _dc:description_
      - _dc:identifier_ (voor de URL)

Om zodoende alleen gebruik te maken van dc als extra ontologie

**Comment by RiX012** [comment]
Wat er nu in de tekst staat kan ik het mee eens zijn.

**Comment by Bakkej** [comment]
Wat betreft brongebruik is het [plaatje ](https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/issues/20#issuecomment-979234877) hierboven denk ik hoe het er qua structuur uit moet zien en iedereen is het daar wel over eens. De discussie lijkt nog vooral te gaan over hoe we "Bron" moeten vertalen. 
We zien opties in bijvoorbeeld FOAF, DCTERMS en FRBR.

Ik denk dat we ook nog moeten overwegen om géén restricties op de rdf:type van de 'Bron' te leggen. De opties zijn namelijk allemaal goed en worden ook _gebruikt_.
Het geen restrictie leggen op het type van de bron maakt het verwijzen naar externe bronnen veel flexibeler. Ik verwacht namelijk dat we op veel 'bronnen' geen invloed hebben en veel van die bronnen niet getypeerd zijn als foaf:Document.
Als we wél een restrictie leggen zal je merken dat de shacl-validatie meldingen zal geven wanneer:
1.  de 'bron' wel als LD gepubliceerd is maar niet (expliciet) een foaf:Document is.
2.  de 'bron' niet als Linked Data gepubliceerd is (en dus ook niet (expliciet) een foaf:Document is)

Als reactie zal men of, zelf statements toevoegen aan eigen dataset zoals:
```<#externe-bron> rdf:type foaf:Document .``` (Kan alleen als de externe bron al als LD gepubliceerd is, opzich ook niet heel erg, maar suboptimaal)
Of een nieuwe resource maken met een verwijzing naar de url van de externe bron:
```<#bron> rdf:type foaf:Document ; <#url> <#externe-bron.url> .```
Dit is goed. Maar het is wel zonde wanneer een bron al als linked data ontsloten is, maar je er niet naar mag verwijzen omdat het toevallig niet expliciet een foaf:Document is.

Op het profiel kan dit het volgende effect hebben.
Wanneer je zelf resources beheert die een bron kunnen zijn, is het logisch/handig deze (ook) te typeren als foaf:Document. We kunnen daarom in het profiel een goodpractice opnemen als: 'Sources SHOULD be typed as foaf:Document'.

Voorbeeld van een profiel in shacl waar er geen restrictie ligt op het type van een bron:
```
skos-ap-nl:Concept a sh:NodeShape:
sh:targetClass skos:Concept ;
  sh:property [ 
    sh:path dct:source ;
    sh:node skos-ap-nl:Bron 
  ]
.
skos-ap-nl:Bron a sh:NodeShape ; # Hier dus geen targetClass
  sh:property [
    sh:name "label" ;
    sh:datatype xsd:string ;
  ] , [
    sh:name "omschrijving" ;
    sh:datatype xsd:string ;
  ] , [
    sh:name "url" ;
    sh:datatype xsd:anyURI ;
  ]
.
```

**Comment by architolk** [comment]
Klinkt goed Jesse! Laten we dat als rationale erbij zetten. En dan vervolgens de mogelijkheid geven om te kiezen uit enkele opties als je zelf de bron vastlegt (bv: als de bron waarna je verwijst geen metadata in Linked Data heeft).

**Comment by ArjenSantema** [comment]
Jesse en Arjen pakken het op om dit in het profiel op te nemen.

**Comment by architolk** [comment]
Arjen en Jesse passen de tekst en het profiel aan conform voorstel Jesse

**Comment by ArjenSantema** [comment]
is uitgewerkt en voldoende beschreven
