### ISSUE TITLE
Kan één begrip voorkomen binnen meerdere contexten?

### ISSUE THREAD

**Issue by FinnTiebout** [pldn/nederlands-profiel-voor-stelselcatalogi#22]
Kan één begrip voorkomen binnen meerdere contexten?

Kan een begrip (concept) voorkomen binnen meerdere contexten? 
Of maken we binnen beide 'contexten' het begrip aan en verwijzen we naar elkaar middels _same as_ ?

**Comment by ArjenSantema** [comment]
Op een aantal plekken gebruiken we de concepten 'begrippenkader' en 'begrippenstelsel'. Beiden kun je definiëren als skos:ConceptScheme

- Een voorbeeld van een begrippenkader is de verzameling van alle begrippen in de BRK. Voor het begrippenkader geldt: brk:Perceel skos:inScheme brk:Begrippenkader.
- Een voorbeeld van een begrippenstelsel is de stelselcatalogus voor de basisregistraties. Je kunt dan eenvoudig het begrip Perceel met alle eigenschappen die in het BRK begrippenkader zijn gedefinieerd opnemen in deze stelselcatalogus door in de stelselcatalogus het statement brk:Perceel skos:inScheme scb:Stelselcatalogus op te nemen.
- Op dezelfde wijze kun je het begrip Perceel opnemen in de stelselcatalogus voor het DSO en in de stelselcatalogus voor Zorgeloos Vastgoed.

Dit is een belangrijke use case voor de standaard waar we hier aan werken.

**Comment by pmaria** [comment]
Zowel een 'begrippenkader' als een 'begrippenstelsel' is dan een instantie van `skos:ConceptScheme`?

Dat is niet handig. Je kunt dan geen onderscheid maken tussen deze concepten.

Vraag: Waarom hebben we een begrippenstelsel nodig in dit profiel?

**Comment by KoosBoersma** [comment]
Eens met Pano. Wij maken een profiel voor één begrippenstelsel binnen één context. Dat je aan je begrippenstelsel een context koppelt is dan op algemeen niveau en van toepassing op het hele begrippenstelsel. 
Met dit als uitgangspunt is het voorkomen van één begrip binnen meerdere contexten niet aan de orde. 
Als een begrip wel in meerdere contexten voorkomt, zou dat betekenen in meerdere begrippenkades (lees woordenboeken).

Als we met het profiel dus ook nastreven dat we een verzamelwoordenboek kunnen maken. Dan wordt deze interessant. Maar is dit het doel van het profiel?

**Comment by GeraldGrootRoessink** [comment]
Een verzamelwoordenboek is meen ik ook de insteek van ISO 25964.  the international standard for thesauri and interoperability with other vocabularies

**Comment by FinnTiebout** [comment]
conclusie: eenzelfde begrip (concept) kan inderdaad binnen meerdere contexten voorkomen. 
twee best practices
- mogelijkheid bieden om tussen twee concepten een relatie te kunnen maken met de betekenis 'is hetzelfde als'
- toestaan dat één begrip binnen meerdere semantische contexten voor kan komen

@FinnTiebout op de agenda voor de volgende keer om toe te wijzen.

**Comment by RiX012** [comment]
BInnen de ISO25964 wordt tevens onderkent dat een term meerdere keren kan voorkomen. Best practice is dan om tussen haken de context te plaatsen. E.g. Bank (Zitobject) en Bank (Financiele instelling)

**Comment by pmaria** [comment]
Is dit een beschreven best practice? Heb je daar een bron van?

Mijn voorkeur heeft:
* voorkeursterm zonder context
* presentatienaam met context

Rationale: de voorkeursterm is de daadwerkelijke term zoals deze lexicaal gebruikt wordt. Deze kan ook gebruikt worden voor andere doeleinden dan presentatie voor de menselijke eindgebruiker, bijv. search,  concept-extractie, etc.
Deze wil je niet "vervuilen".

De presentatienaam kan dan gebruikt worden voor disambiguatie van conflicterende voorkeurstermen bij presentatie, bijv. in UIs

**Comment by RiX012** [comment]
> Is dit een beschreven best practice? Heb je daar een bron van?

De ISO25964-1 en dan specifiek hoofdstuk 6.2.2.
![afbeelding](https://user-images.githubusercontent.com/56293445/170700980-a0edda07-d9d6-41c1-9e4a-4189b0dac5be.png)

**Comment by architolk** [comment]
Drie scenario's:
a) Overlappende contexten waar je zelf eigenaar van bent;
b) Overlappende contexten, waarbij meerdere eigenaren zijn (en jij bent eigenaar van de context waar je naar verwijst);
c) Overnemen in jou catalogus (administratief), zonder dat je een nieuw begrip wilt bedenken.
