### ISSUE TITLE
profiel (ttl) splitsen in abstracte beschrijving en een shape

### ISSUE THREAD

**Issue by FinnTiebout** [pldn/nederlands-profiel-voor-stelselcatalogi#23]
Momenteel is het profiel in één bestand vastgelegd. 
@architolk @pmaria @ArjenSantema gaan bespreken of het beter is hier twee verschillende bestanden van te maken. 
1. abstarcte beschrijving
2. shape.

**Comment by ArjenSantema** [comment]
In https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/blob/main/concepts/thesaurus.ttl is een eerste opzetje gemaakt voor de beschrijving. Deze beschrijving is gemaakt in Skos. Daarmee kun je zowel Nederlandstalige labels opnemen als een vertaling van de definitie en een scope note die aangeeft hoe wij dit element in onze standaard gebruiken. Deze opzet is overgenomen van de nationale politie. 
De shape op https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/blob/main/profiles/skos-ap-nl.ttl kan dan worden uitgekleed, zodat alleen de structuur overblijft.

**Comment by ArjenSantema** [comment]
in specificatie gereed, nog doorvoeren als 2 tabellen in Respec
