### ISSUE TITLE
Is onderdeel van relatie in fysieke vorm

### ISSUE THREAD

**Issue by KoosBoersma** [pldn/nederlands-profiel-voor-stelselcatalogi#25]
Een gemaal heeft een pomp als onderdeel van het gemaal. Echter een pomp is niet een smallere relatie van een gemaal.

Bovenstaande relatie maken we van een asset perspectief. Vraag is op welke manier zouden we deze in begrippenkader kunnen opnemen door dit in ... relaties te verwoorden. 

In de Aquo hebben we daar nu de "heeft onderdeel" relatie voor staan. Echter deze is niet twee kanten op gemoduleerd. 
Graag jullie input op dit vraagstuk.

**Comment by ArjenSantema** [comment]
Volgens mij zijn er 2 mogelijkheden:
1) een skos:related relatie tussen 'pomp' en 'gemaal'. Je kunt dan alleen niet meer zien dat een pomp onderdeel van een gemaal is.
2) een skos:narrower of nog iets nauwkeuriger een skosthes:narrowerPartitive relatie tussen een 'pomp (gemaal)' of 'gemaalpomp' en gemaal. Je moet 'pomp' dan wel specificeren want 'pomp' in het algemeen is natuurlijk geen onderdeel van een gemaal, dan zou ook een fietspomp onderdeel van een gemaal worden.

**Comment by pmaria** [comment]
Mijn vraag is: Waarom zou je dit in een begrippenkader willen opnemen als onderdeel van de modellering van een begrip?

Dit kun je volgens mij beter modelleren in een ontologie/informatiemodel, waar je overgaat van beschrijven van begrippen naar beschrijven van hoe dingen (referenten van de begrippen) zich tot elkaar verhouden en welke kenmerken deze dingen nog meer hebben.

**Comment by ArjenSantema** [comment]
Als je een gemaal definieert als 'een gebouw waarin water van een laag naar een hoog niveau wordt gepompt' wordt de betekens van het begrip 'gemaal' mede bepaald door de betekenis van het begrip 'pomp'. Een pomp heeft weer een 'Capaciteit', etc. In dat geval zou ik de relatie tussen een gemaal en een pomp in het begrippenkader willen opnemen. 
Binnen het Kadaster hebben we dat soort relaties bijvoorbeeld tussen percelen, grenzen en Nederlands grondgebied.  'Perceel' wordt gedefinieerd als 'begrensd deel van het Nederlands grondgebied dat kadastraal geïdentificeerd is en met kadastrale grenzen begrensd is.'

**Comment by pmaria** [comment]
Maar is het begrip - de gedachte over - het perceel dan onderdeel van het het begrip - de gedachte over - Nederlands Grondgebied?

Wat betekent het überhaupt dat een begrip - de gedachte over iets - onderdeel is van een ander begrip  - de gedachte over iets anders?

Of bedoel je dat het begrip Nederlands grondgebied gebruikt wordt in de definitie van het begrip Perceel? Dan ligt de relatie misschien zelfs andersom? De gedachte over Nederlands grondgebied is onderdeel over mijn gedachte over Perceel...

Dat de begrippen gerelateerd zijn aan elkaar betwist ik niet. Maar de "is-onderdeel-van" relatie kan ik nog niet inbeelden.

**Comment by KoosBoersma** [comment]
Aanvulling. 
Intern hebben we de discussie ook lopen. Doel van de relatie is ook vanuit een assetmanagement perspectief de relaties tussen verschillende begrippen aan te kunnen geven. 
Dus breder en smaller gebruiken we voor hiërarchie (taxonomie) en de "isPartOf" voor de asset onderdeel relatie.

Wij komen in de discussie uit op DublinCore en dan de isPartOf : https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/isPartOf/ specificatie welke omgedraaid de relatie "HasPart" heeft. 

Ik begreep dat deze relatie ook binnen GWSW gebruikt wordt. 
Met deze mogelijke keuze gebruiken we expres verschillende relaties voor verschillende doelen.

Hoe zit dit bij jullie?

**Comment by GeraldGrootRoessink** [comment]
Ik neem aan dat met assetmanagement het beheer van assets wordt bedoeld. Dan zijn we naar mijn idee al verder in het voortbrengingsproces,  waarbij de relaties zijn uitgewerkt in klassen en attributen en dergelijke.

**Comment by RiX012** [comment]
Ik zou dit ook niet zien als een onderdeel van een profiel voor stelselcatalogi, maar dat iets dergelijks pas in een formele ontologie komt. De broader/narrower structuur zou hier ook niet voor toegepast moeten worden. 
dct:isHasPart kan wel, dat staat de opsteller natuurlijk vrij. Maar niet als onderdeel van het profiel

**Comment by architolk** [comment]
skos-thes biedt hier de mogelijkheid voor. Dit zijn specialisaties van skos:broader en skos:narrower, die slechts stellen dat een term een bredere dan wel smallere betekenis beoogd. in skos-thes heb je (conform ISO) de volgende mogelijkheden:
- generalisatie / specialisatie (broaderGeneric / narrowerGeneric)
- part of / has part (broaderPartitive / narrowerPartitive)
- instantie van / categorie van (broaderInstantive / narrowerInstantive)

**Comment by architolk** [comment]
Zie ook #27

**Comment by RiX012** [comment]
> skos-thes biedt hier de mogelijkheid voor. Dit zijn specialisaties van skos:broader en skos:narrower, die slechts stellen dat een term een bredere dan wel smallere betekenis beoogd. in skos-thes heb je (conform ISO) de volgende mogelijkheden:
> 
>     * generalisatie / specialisatie (broaderGeneric / narrowerGeneric)
> 
>     * part of / has part (broaderPartitive / narrowerPartitive)
> 
>     * instantie van / categorie van (broaderInstantive / narrowerInstantive)

Prima, maar ik blijf bij het punt dat dit niet in een profiel voor stelselcatalogi een uitgangspunt zou moeten zijn.

**Comment by ArjenSantema** [comment]
Staat als onderdeel van iso-thes in de beschrijving
