### ISSUE TITLE
Hiërarchie structuren van de verschillende vormen

### ISSUE THREAD

**Issue by KoosBoersma** [pldn/nederlands-profiel-voor-stelselcatalogi#27]
Beschrijven wat we verstaan onder de verschillende types en hoe we daarin realties gebruiken.

Begrippenlijsten: Simpele lijst zonder hiërarchie
Taxonomie: Begrippen met een .... hiërarchie.  bv. Alleen breder/smaller en relateert en volgt informatie model x
Thesaurus: Begrippen met meerdere hiërarchie modellen. Dus breder/smaller maar ook isPartOf/HasPart en ..... Hierin beschrijven we ook waarvoor welke relatie wordt gebruikt.
Thesaurus met extra semantiek: TODO
Ontologie: ambitie wat mij betreft

Moeten we dit uitwerken???

**Comment by GeraldGrootRoessink** [comment]
In MIM heet het Model van begrippen voor een domein. Gaat ook over onderlinge relaties. Maar is dat hetzelfde/
Thesaurus is domeinoverstijgend: zie ISO 25964 – the international standard for thesauri and interoperability with other vocabularies

**Comment by architolk** [comment]
De uitbreiding van http://purl.org/iso25964/skos-thes biedt de link tussen SKOS en ISO 25964, daarin wordt skos:broader en skos:narrower verder gespecialiseerd. Skos-thes is mede gemaakt door dezelfde auteurs als skos (zoals Antoine Isaac)

**Comment by FinnTiebout** [comment]
https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/issues/21

**Comment by RiX012** [comment]
> Beschrijven wat we verstaan onder de verschillende types en hoe we daarin realties gebruiken.
> 
> Begrippenlijsten: Simpele lijst zonder hiërarchie Taxonomie: Begrippen met een .... hiërarchie. bv. Alleen breder/smaller en relateert en volgt informatie model x Thesaurus: Begrippen met meerdere hiërarchie modellen. Dus breder/smaller maar ook isPartOf/HasPart en ..... Hierin beschrijven we ook waarvoor welke relatie wordt gebruikt. Thesaurus met extra semantiek: TODO Ontologie: ambitie wat mij betreft
> 
> Moeten we dit uitwerken???

Wellicht helpt het om het Begrippenkader van het Informatiemodel (né Ontologie) te scheiden. 
Het begrippenkader kan inderdaad vervolgens een Begrippenlijst, Vocabulaire (Begrippenlijst+Taxonomie), Thesaurus zijn.

De uitwerking van het profiel zou wat mij betreft deze laatste drie niveaus moeten dienen. Waarbij wat mij betreft de gebruiker/opsteller gewoon kiest wat hij nodig heeft. Strikte scheiding is wat mij betreft niet nodig.

**Comment by architolk** [comment]
Zie ook #25
