### ISSUE TITLE
Thesaurus - definitie en uitleg

### ISSUE THREAD

**Issue by ArjenSantema** [pldn/nederlands-profiel-voor-stelselcatalogi#3]
Stelling:

1. Good practice: een definitie is altijd scherp en waterdicht. Neem deze waar mogelijk 1 op 1 over uit een officiële bron zoals de wet.
2. Good practice: gebruik een standaard patroon voor een definitie, bijvoorbeeld <een .... is ....>.
3. Good practice: leg een concept altijd uit in gewone-mensentaal (taalniveau B2), ook al gaat dit ten koste van de sluitendheid van de definitie (juridische definities zijn meestal met een reden moeilijk leesbaar). Gebruik voor deze uitleg het rdfs:comment.

**Comment by GeraldGrootRoessink** [comment]
ad 1) overnemen?  dan ook herkomst of verwijzing
ad 2)  wij zeggen:  een bli is een bla die bloept.
ad 3)  om dicht bij skos te blijven kunnen we ook skos:scopeNote gebruiken

**Comment by FinnTiebout** [comment]
Conclusie:

1. skos:Defintion indien bron aanwezig, overnemen uit die bron en verwijzen naar de bron. 
Indien geen bron aanwezig, zelf een definitie opstellen. Definitie dient kort en bondig te zijn. 
2. Hoe een definitie inhoudelijk is opgesteld zijn we het nog niet over eens, daar komt een nieuw issue voor. 
https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/issues/16
3. definitie is niet persé in gewone-mensentaal, daar kan een subpropertie van skos:definitie voor gebruikt worden.
skos:definition is de officiële definitie.
Verdere discussie rondom toelichting, voorbeelden etc. wordt besproken in https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/issues/13
