### ISSUE TITLE
Uniciteit van prefLabel binnen een context

### ISSUE THREAD

**Issue by architolk** [pldn/nederlands-profiel-voor-stelselcatalogi#31]
Ook gerelateerd aan #22 (zie daar ook voor verwijzing naar de ISO standaard).

Het lijkt me een best practice dat een begrip binnen één concept een unieke prefLabel heeft, hoe kun je binnen die context immers anders je duidelijk uitdrukken? Ook in definities leidt dat tot problemen, je weet dan niet meer waar je naar verwijst.

Voorstel aanpassing: best practice is dat ene prefLabel uniek is binnen de context (dwz: het ConceptScheme)

**Comment by lvdbrink** [comment]
Een uniek prefLabel binnen één taal dan wel (zie ook #35).

**Comment by GeraldGrootRoessink** [comment]
Ik ben een beetje los, eerlijk gezegd. 
Eén preflabel per taal: ok, zo staat het ook in SKOS
Eén  preflabel per context: ?? Dat staat niet zo in SKOS.
Wat ik daar wel lees:  een begrip/concept heeft één preflab (minimaal en maximaal)
En in #22 lees in dat een begrip/concept in meerdere contexten/conceptschemes kan voorkomen.
Dat is tegenstrijdig met de hierboven voorgestelde best practice.

**Comment by architolk** [comment]
@Bakkej : inderdaad. Begrip = voorkeursterm + betekenis in een context, dus andere voorkeursterm = ander begrip.

**Comment by ArjenSantema** [comment]
Een begrip heeft altijd 1 prefLabel in een bepaalde taal in een bepaalde context. Het issue ontstaat bij gebruik van hetzelfde prefLabel in verschillende contexten komt terug in issue #22.

**Comment by pmaria** [comment]
Deze passage klopt volgens mij niet:
https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/blob/6688c13ae01ab0ac75ef0a4205f5e36d8c523063/respec/Begrip.md?plain=1#L4-L6

Volgens mij zou het juist **niet** mogelijk moeten zijn dat binnen een bepaald domein (begrippenkader) een term met verschillende definities voorkomt.

**Comment by architolk** [comment]
Inderdaad... ik had de tekst daarboven aangepast, maar deze regel over het hoofd gezien: ik heb de regel weggehaald (voegt nu niets meer toe)

**Comment by architolk** [comment]
Voor zover ik kan zien, is dit issue nu opgelost.

**Comment by Bakkej** [comment]
Voldoende beschreven in de standaard
