### ISSUE TITLE
Begrippenkader vs Begrippenstelsel

### ISSUE THREAD

**Issue by architolk** [pldn/nederlands-profiel-voor-stelselcatalogi#32]
De termen "Begrippenkader" en "Begrippenstelsel" worden beiden gebruikt. Daarbij lijkt "Begrippenkader" de beschrijving van zowel begrippen als het begrippenstelsel, terwijl begrippenstel overeen lijkt te komen met een skos:ConceptScheme. Maar soms lijken het echter synoniemen (bijvoorbeeld in de formele definitie van "Begrippenkader" => "een begrippenstelsel is een..." :-D

In SKOS is een skos:ConceptScheme geen beschrijving van begrippen: het is een op zichzelfstaand element, waarbij van begrippen kan worden gezegd dat ze "in" een conceptschema zitten. Daarmee zit niet de beschrijving in het skos:ConceptScheme, maar juist het begrip (skos:Concept) zelf. Het drukt feitelijk uit in welke context het begrip zit. Het is dan ook mogelijk (volgens het skos formele model) dat een skos:Concept in meerdere skos:ConceptScheme's zit.

Veel tools gaan er overigens iets strikter mee om, en gaan er vanuit dat er een 1-op-1 relatie ligt tussen beiden.

Voor het profiel lijkt het me relevant om (a) onderscheid te maken en (b) hiervoor termen benoemen die we gaan gebruiken.

**Comment by RiX012** [comment]
Ik vind deze semantische discussie wel passen in deze plaat: https://twitter.com/krabina/status/1532674823121514496/photo/1

`skos:ConceptScheme` is inderdaad losje gedefinieerd. Maar in het SKOS <> ISO25964 samenspel wordt als best practice geadviseerd om `skos:ConceptScheme`  en 'Thesaurus' gelijk te stellen. Daarmee zou je kunnen zeggen dat het een afgebakende set van termen en relaties is. 

Het 'Begrippenkader' is wat mij betreft dan de totale verzameling van begrippen en alles wat je daar over zou willen vastleggen binnen een bepaald doel. Daarbinnen kunnen dus meerdere `skos:ConceptScheme` vallen, die thesauri representeren.

Het `Begrippenstelsel' is wat mij betreft het geheel aan (gelinkte) begrippen. Dus ook degene die buiten het doel van het op dat moment beschouwde Begrippenkader vallen.

**Comment by pmaria** [comment]
Ik denk dat ik me wel kan vinden in wat @RiX012 beschrijft.

Daarbij zou ik Begrippenstelsel niet expliciet onderdeel maken van het profiel.

Je zou het wel kunnen introduceren als term, en wellicht zelfs beschrijven in een conceptueel model. Maar, niet als iets wat je zult uitwisselen conform dit profiel.

**Comment by architolk** [comment]
Prima, dus:
- Begrippenkader: het gehele model dat je hebt vastgelegd, kan eventueel meerdere skos:ConceptScheme(s) omvatten;
- Begrippenstelsel: het geheel aan (gelinkte) begrippen, kunnen ook begrippen buiten het begrippenkader zijn.

Vraag die ik dan nog wel heb:is een skos:ConceptScheme dan 1 van deze 2? Niet de eerste, maar wel de tweede? Of hanteren we nog een derde term?

**Comment by architolk** [comment]
Arjen neemt mee in de redactieslag

**Comment by pmaria** [comment]
> Begrippenkader: het gehele model dat je hebt vastgelegd, kan eventueel meerdere skos:ConceptScheme(s) omvatten;

Zo had ik begrippenkader zelf niet in mijn hoofd. Ik zag begrippenkader en `skos:ConceptScheme` als hetzelfde Toont volgens mij het belang aan van eerst het SKOS onafhankelijke abstracte model met elkaar duidelijk krijgen (re: #37).

**Comment by architolk** [comment]
> > Begrippenkader: het gehele model dat je hebt vastgelegd, kan eventueel meerdere skos:ConceptScheme(s) omvatten;
> 
> Zo had ik begrippenkader zelf niet in mijn hoofd. Ik zag begrippenkader en `skos:ConceptScheme` als hetzelfde. Toont volgens mij het belang aan van eerst het SKOS onafhankelijke abstracte model met elkaar duidelijk krijgen (re: #37).

In ieder geval zijn er nu twee termen die niet als synoniemen van elkaar worden gepositioneerd: Begrippenkader en Begrippenstelsel. Als die twee wel synoniem van elkaar zijn, dan hebben we maar 1 van de 2 termen nodig. En dan missen we nog een term voor het andere begrip. Dus in een abstracte syntax: We hebben een abstractie <BN>, met betekenis "semantisch samenhangend geheel van <B>'s", waarbij <B> een begrip is. En <BA>, met betekenis "geheel van beschrijvingen van <B>'s die als 1 geheel worden beheerd.

**Comment by pietervaneverdingen** [comment]
Een begrippenstelsel is meer op macro- en meso-niveau en een begrippenkader meer op micro-niveau.

Een begrippenstelsel is dan een verzameling op elkaar afgestemde begrippenkaders binnen een domein of stelsel, bijv. een begrippenstelsel voor alle begrippenkaders binnen het onderwijs. Zo is het nu ook al beetje voorgesorteerd in BegrippenXL en maakt het verschil makkelijker om te duiden. En een begrippenstelsel op meso-niveau kan dan weer onderdeel zijn van een begrippenstelsel op macro-niveau. Zo, kan het begrippenstelsel voor het onderwijs weer onderdeel zijn van het begrippenstelsel voor alle begrippenkaders binnen de overheid (die dan ook weer verder op elkaar afgestemd kunnen worden om onnodige overlap en beter hergebruik van elkaars begrippen te verhogen).

**Comment by architolk** [comment]
Voor nu is het "opgelost" door de opmerking over de combinatie van skos:ConceptScheme en adms:Asset. Daarmee is "begrippenstelsel" als afzonderlijk begrip vervallen uit ons profiel en hanteren we slechts de term "begrippenkader". Daarmee is het issue feitelijk nog niet opgelost, maar wel voldoende voor deze eerste versie van het profiel: we hebben het simpelweg nog niet over het verschil tussen een semantisch begrippenstelsel, en het beheerde begrippenkader (verschil tussen een stelsel van begrippen of een samenhangende beschrijving van deze begrippen)

**Comment by pmaria** [comment]
Ik snap niet helemaal de rol van `adms:Asset` in de oplossing. Daarnaast, welke onderdelen van ADMS zouden we hier willen gebruiken en waarom?

**Comment by architolk** [comment]
Het gaat niet zozeer over wat je er uit zou willen gebruiken, maar wat je er mee bedoeld. Strikt genomen is een skos:ConceptScheme niet gelijk aan een set van triples (die gezamenlijk de begrippen beschrijft die een skos:inScheme relatie hebben met dat skos:ConceptScheme). Dat doen wij (dus) wel: het is een beheerde "asset", dwz: een product met waarde.

**Comment by pmaria** [comment]
Ok. Volgens mij is dit wel iets heel fundamenteels.
De definitie van begrippenkader is nu: 
> Het begrippenkader is het geheel van de begripsbeschrijvingen die als één geheel worden beheerd.

Hierbij wordt dus gesteld dat een begrippenkader een eenheid van beheer is, en het gebruik van `adms:Asset` versterkt dat.

Echter, bij de beschrijving van begrip staat:

> De context wordt gevormd door het begrippenkader waarbinnen het begrip zich bevindt, context is de universe of discourse.

Wat is het nou? Eenheid van beheer of eenheid van context? Of, is het beide? Dat kan, maar is dat handig?

Volgens mij is het sowieso van belang om een model van beheer te scheiden van een model van betekenis. En ik denk ook dat we ons eerst moeten focussen op het model onafhankelijk van beheers- en registratieaspecten. Daarna kunnen we bepalen welke vormen van beheer- en registratieaspecten relevant zijn om uit te werken in dit profiel.

**Comment by architolk** [comment]
Afgesproken: werkgroepje die begrip vs begripsbeschrijving / verzameling-begrippen vs verzameling-begripsbeschrijvingen gaat voorbereiden: (a) elevator pitch wat het probleem is; (b) goede beschrijving maken van de twee concepten die we nodig hebben, en de juiste terminologie daarbij

**Comment by RiX012** [comment]
Prima om wat mij betreft `begrippenstelsel` impliciet te laten en niet te definiëren. In de lopende tekst wordt wel bijvoorbeeld wel gesproken over 'stelsel van begrippen'. Maar goed, een `enhancement` dus.

**Comment by Bakkej** [comment]
Gemarkeerd als Enhancement.
Huidige standaard beperkt zich tot 'begrippenkader'.

**Comment by ArjenSantema** [comment]
Het begrip 'begrippenstelsel' komt nu nergens meer voor. Als dat in het kader van een stelselcatalogus toch nog nodig blijkt te zijn, komt het dan wel opnieuw naar voren.
