### ISSUE TITLE
Engelse definities/toelichtingen in bijlage

### ISSUE THREAD

**Issue by architolk** [pldn/nederlands-profiel-voor-stelselcatalogi#33]
De Engelse definities/toelichtingen zijn opgenomen om zeker van te zijn dat we geen nieuwe betekenis geven aan de bestaande vocabulaires die we gebruiken (skos, Dublin core, etc).

Echter, in hoofdstuk twee (profiel) is het wat overdreven om deze engelstalige definities/toelichtingen neer te zetten. Dit zou ook in een bijlage kunnen.

BESLUIT (in overleg van 23-6):
a) In de turtle bestanden nemen we de exacte Engelstalige definities/toelichtingen/termen op zoals in de originele vocabulaires;
b) in hoofdstuk 2 (profiel) tonen we alleen het Nederlands (dus we tonen niets als er geen Nederlands is);
c) in een bijlage geven we een tabel met de verantwoording: Nederlands vs Engels.

**Comment by ArjenSantema** [comment]
Engelse labels zijn overgeheveld naar bijlage.
