### ISSUE TITLE
Toevoegen hoofdstuk "rationale/use case" tussen de inleiding en het daadwerkelijke profiel

### ISSUE THREAD

**Issue by architolk** [pldn/nederlands-profiel-voor-stelselcatalogi#34]
Het is niet helemaal duidelijk waarom bepaalde elementen zijn opgenomen in het profiel: waarom juist deze? Dit hangt samen met een "verhaaltje" over het gebruik van het profiel, en de use cases.

BESLUIT
Er komt een hoofdstuk tussen de inleiding en het profiel waarin duidelijk wordt beschreven (in tekst) wat de rationale is voor het model.

**Comment by ArjenSantema** [comment]
hoofdstuk is toegevoegd. Opmerkingen over de inhoud kunnen naar aanleiding van de tekst.
