### ISSUE TITLE
Meertaligheid van eigenschappen

### ISSUE THREAD

**Issue by JosVanderArend** [pldn/nederlands-profiel-voor-stelselcatalogi#35]
Er wordt nog niets geschreven over de meertaligheid van eigenschappen. Er is in een begrippenkader vaak behoefte aan waarden in meer dan 1 taal, bijvoorbeeld voorkeursterm in Engels en Nederlands. Blijft dat zo?

**Comment by RiX012** [comment]
In principe kunnen hier toch de SKOS 'regels'  voor gehanteerd worden? Ieder concept kan een @nl en @en hebben per literal

**Comment by architolk** [comment]
> In principe kunnen hier toch de SKOS 'regels' voor gehanteerd worden? Ieder concept kan een @nl en @en hebben per literal

+1

**Comment by KoosBoersma** [comment]
o	https://www.w3.org/wiki/SkosCoreGuideToc/SectionMultilingual

Voorbeeld van meertalige implementatie.

**Comment by architolk** [comment]
Voor zover ik kan zien, is dit nu in de beschrijving goed opgenomen. Niet helemaal zeker of het SHACL profiel dit nu ook correct doet.

**Comment by Bakkej** [comment]
Naar tevredenheid in het profiel verwerkt
