### ISSUE TITLE
Concept en begrip wordt door elkaar heen gebruikt

### ISSUE THREAD

**Issue by pmaria** [pldn/nederlands-profiel-voor-stelselcatalogi#36]
In het document wordt 'concept' en 'begrip' afwisselend gebruikt. Dit helpt de lezer niet. We kunnen 1 keer benoemen dat 'concept' en 'begrip' synoniem zijn en dan vervolgens onze voorkeursterm gebruiken in de rest van het document. Mijn voorkeur gaat uit naar 'begrip'.

**Comment by ArjenSantema** [comment]
Opgelost met pull request nav issue 32. Overal begrip als term gebruikt.
