### ISSUE TITLE
Mapping naar SKOS en andere vocabs lostrekken van abstracte beschrijving standaard

### ISSUE THREAD

**Issue by pmaria** [pldn/nederlands-profiel-voor-stelselcatalogi#37]
Momenteel is het document zo opgezet dat de mapping naar SKOS, direct bij de abstracte beschrijving van de informatie-elementen voor het beschrijven van begrippen zit. Er wordt ook gesteld:

> Praktisch betekent dit dat dit profiel primair een profiel is voor de toepassing van SKOS. In het kader van 'practice what you preach' worden alle gebruikte concepten in dit profiel beschreven in SKOS, toegepast volgens dit profiel. Alle definities van de concepten zijn 1 op 1 overgenomen uit de SKOS primer.

Hier ben ik het fundamenteel mee oneens. Dit profiel moet m.i. in de kern onafhankelijk van SKOS worden opgesteld. Het doel is om een gedeeld beeld en gedeelde taal te hebben om begrippenstelsels te beschrijven en uit te wisselen. Dat betekent dat we in eerste instantie een abstract informatiemodel / abstracte syntax moeten definiëren om dat te kunnen en waarover we het met elkaar eens zijn. 

Vervolgens kan dit gemapt worden naar SKOS en andere vocabulaires voor een LD / SKOS-gebaseerd profiel. Maar, kan het ook gemapt worden naar een standaard JSON of XML schema, onafhankelijk van SKOS, waardoor het nog breder geadopteerd kan worden. 

Uiteraard kunnen we ons laten inspireren door SKOS (zodat het ook goed past) en relevante ISO-standaarden, maar we lijken het nu om te draaien.

De mappping naar SKOS en andere vocabulaires zou ik dan graag als een apart hoofdstuk zien, los van de definities in het abstracte informatiemodel.

**Comment by architolk** [comment]
Dit kan denk ik relatief makkelijk:
- We hanteren Nederlandstalige labels voor ons profiel. Dit zijn geen SKOS termen.
- We hebben al aangegeven dat we de Engelstalige definities naar de bijlage zouden verplaatsen:
- Onze eigen definities zijn dus prima in in het Nederlands als onderdeel van de abstracte syntax;
- In SHACL kun je prima stellen dat als je de sh:targetClass en sh:path weglaat, je feitelijk de abstracte syntax overhoudt.

Volgens mij is het wel zo, dat we uiteindelijk wel kiezen voor SKOS, omdat deze het beste past.

**Comment by ArjenSantema** [comment]
Marco heeft al een en ander voorbereid (zie pull request nav issue 32). Verder uitwerken door Pano, Jesse, Marco.

**Comment by pmaria** [comment]
> In SHACL kun je prima stellen dat als je de sh:targetClass en sh:path weglaat, je feitelijk de abstracte syntax overhoudt.

Dat kan op zich, maar is denk ik verwarrend omdat gebruik van SHACL normaal gebruikt wordt in een RDF-wereld.
Veel liever zou ik zien dat we als basis een abstracte beschrijving hebben zonder SHACL. Een mogelijkheid zou kunnen zijn om een MIM (niveau 2) model incl UML gebaseerde visualisatie hier voor te gebruiken. 
Dit geeft mijns inziens een implementatie onafhankelijke basis.

In het Linked data profiel kan vervolgens het SHACL profiel de mapping naar RDF vocabulaires invullen.

Daarnaast kunnen er ook andere mappings gemaakt worden op dezelfde basis. Bijvoorbeeld naar een JSON-schema voor gebruik in API's.

> Volgens mij is het wel zo, dat we uiteindelijk wel kiezen voor SKOS, omdat deze het beste past.

Eens. Maar het gaat mij erom dat we de basis eerst goed neerzetten, niet gehinderd door ieders eigen bestaande interpretaties van SKOS en andere vocabulaires.

**Comment by architolk** [comment]
Of je het nu in SHACL uitdrukt, of in UML of in MIM => Uiteindelijk komt het op hetzelfde neer: een abstracte representatie van wat we bedoelen. Aangezien we SHACL al hebben, zou ik willen voorstellen om het daar bij te laten, maar wel een UML plaatje daaruit genereren en ook een MIM variant, da's wel zo aardig ;-)

**Comment by Bakkej** [comment]
voldoende verwerkt in het profiel
