### ISSUE TITLE
Thesaurus - semantische relaties binnen thesaurus

### ISSUE THREAD

**Issue by ArjenSantema** [pldn/nederlands-profiel-voor-stelselcatalogi#4]
Stelling:

1. Good practice: gebruik skos-thes voor meer nauwkeurige (transitieve) definitie van specialisaties/generalisaties, partitieve relaties en daarmee compatibiliteit met de ISO 25964-thesaurusstandaard, specifiek skosthes:broaderGeneric, skosthes:broaderPartitive, skosthes:narrowerGeneric en skosthes:narrowerPartitive.
2. Good practice: gebruik skos:semanticRelaton voor andere semantische relaties.

**Comment by pmaria** [comment]
> 1. Good practice: gebruik skos-thes voor meer nauwkeurige (transitieve) definitie van specialisaties/generalisaties, partitieve relaties en daarmee compatibiliteit met de ISO 25964-thesaurusstandaard, specifiek skosthes:broaderGeneric, skosthes:broaderPartitive, skosthes:narrowerGeneric en skosthes:narrowerPartitive.

Persoonlijk zie ik geen noodzaak voor deze relaties. Deze relaties horen wat mij betreft thuis in een specifiek informatiemodel. Het vermengen van deze verschillende soorten relaties in 1 thesaurus leidt ook tot problemen bij het ordenen van begrippen.

**Comment by kad-stapr** [comment]
Het is denk ik goed om vooraf te bepalen welke rol een thesaurus speelt en voor wie. Zo zie ik de thesaurus als een 'tool' om kennis te ordenen voor de mens. Volgens mij is een thesaurus een middel om de juiste term (woord) te vinden bij een begrip (concept? (boven in triangle of meaning)). Daarbij wordt gebruik gemaakt om het woord te duiden ten opzichten van andere woorden die een gelijke- of verwante definitie hebben, zonder exact de betekenisvolle relatie uit te drukken. Om zo'n thesaurus in digitale vorm uit te drukken is skos/skosthes denk ik een voor de hand liggend middel.
Het andere aspect gaat over de modellering van 'real world things' (rechtsonder in triangle of meaning) en waarvoor een gedetailleerder model nodig is om de 'things' en de betekenisvolle relaties tussen de 'things' te kunnen uitdrukken. Volgens mij is dat ook wat Pano bedoel met het 'specifieke informatiemodel'? 
Ik denk dat het goed is om hierover een gemeenschappelijk inzicht te ontwikkelen en we weten wat bedoeld wordt met semantische relaties tussen concepten in een thesaurus model en semantische relaties tussen objecten/'things' uit informatie model/ontologie.
