### ISSUE TITLE
Bronvermelding dct:source (of subject)?

### ISSUE THREAD

**Issue by JosVanderArend** [pldn/nederlands-profiel-voor-stelselcatalogi#42]
Ik lees in paragraaf 3.4 bron (https://pldn.github.io/nederlands-profiel-voor-stelselcatalogi/#bron) dat dct:subject wordt gebruikt.

Maar in paragraaf 2.1 lees ik "Daarnaast wordt via [dct:source](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/source) steeds expliciet de relatie gelegd naar de bron(nen) waaraan de beschrijvingen in dit profiel zijn ontleend.".

Wat is juist: dct:source of toch dct:subject?

**Comment by Bakkej** [comment]
Bronverwijzing gaat altijd met dct:source. Dit stond fout in paragraaf 3.4 en is nu aangepast.
