### ISSUE TITLE
Paragraaftitels of niet

### ISSUE THREAD

**Issue by JosVanderArend** [pldn/nederlands-profiel-voor-stelselcatalogi#43]
Tussen paragraaf 3.1 en 3.1.1 staan heel veel kopjes die ook paragraaftitels lijken te zijn. Ze komen echter niet voor in de inhoudsopgave. Wat betekenen die kopjes, bijvoorbeeld zijn het placeholders voor nadere tekstuitwerking?

**Comment by ArjenSantema** [comment]
Paragraaftitels nu 4 niveaus diep.
