### ISSUE TITLE
Simpele SKOS regels

### ISSUE THREAD

**Issue by RiX012** [pldn/nederlands-profiel-voor-stelselcatalogi#45]
Ik kwam deze regels tegen in Semantics Web for the Working Ontologist. 

Wellicht handig om dergelijke uitgangspunten ook op te nemen in deze aanbeveling.

<img width="722" alt="SKOS - SW for the working ontologist" src="https://user-images.githubusercontent.com/56293445/191244988-5e628739-4077-4d66-bee3-e199937061e2.png">

**Comment by Bakkej** [comment]
Vergelijkbare regels zijn ook [hier](https://github.com/cmader/qSKOS/wiki/Quality-Issues#Undocumented_Concepts) gedefinieerd. Deze worden o.a. in [skos-play](https://skos-play.sparna.fr/play/upload#) en in poolparty gebruikt. Het lijkt me inderdaad handig dit ergens terug te laten komen.

**Comment by RiX012** [comment]
Voldoende verwerkt
