### ISSUE TITLE
Thesauri - verbinden met concepten andere thesauri

### ISSUE THREAD

**Issue by ArjenSantema** [pldn/nederlands-profiel-voor-stelselcatalogi#5]
Stelling:

1. Good practice: verbind zoveel mogelijk concepten met concepten uit andere thesauri, zowel van andere domeinen als internationale, meer generieke thesauri (bijvoorbeeld joinup).
2. Good practice: leg deze verbindingen semantisch correct met broadMatch, narrowMatch, closeMatch, exactMatch of relatedMatch.
3. Gebruik voor de verwijzing naar een geschreven bron (digitaal of niet digitaal) dct:source.
4. Gebruik daarbij indien beschikbaar de uri van de bron.

**Comment by kad-tiebof** [comment]
Het is denk ik nuttig om bij relaties duidelijk onderscheid te maken tussen relaties naar concepten binnen het eigen begrippenkader en naar concepten buiten het begrippenkader. Is de huidige manier waarop we dat in de DSO catalogus doen voldoen?

**Comment by pmaria** [comment]
> 4. Gebruik daarbij indien beschikbaar de uri van de bron.

Ik zou willen pleiten voor een generieke manier van het modelleren van bronnen. Met daarbij ondersteuning voor:

* verwijzing naar een webpagina
* verwijzing naar wetgeving
* verwijzing naar een bron die niet op het web bestaat
* verwijzing naar een downloadbare bron

Een requirement is mijns inziens dat we dit met 1 manier van modelleren oplossen. Indien mogelijk natuurlijk. Dat maakt het gemakkelijk voor afnemers om te gebruiken en bijvoorbeeld voor tooling om te presenteren, etc.

**Comment by kad-stapr** [comment]
Het is voor mij nog een vraag waarom we concepten met andere thesauri willen verbinden. Ik kan mij een situatie voorstellen waarbij vergelijkbare thesauri (binnen een vergelijkbaar domein) met elkaar verbonden zouden kunnen worden, maar ik zie een uitdaging voor thesauri die daarbij van andere concepten gebruik maken. Hoe wordt de kwaliteit van de thesaurus bewaakt wanneer andere concepten daaraan worden toegevoegd?
Kortom, wat is de usecase die deze wens rechtvaardigt? 

In aanvulling op het pleidooi van Pano voor de generieke manier van modelleren van bronnen zie ik een toenemende behoefte om onderscheidt te maken tussen de identificatie van de 'abstracte bron' en de representatie van de die bron. In het verleden was een verwijzing naar een bron veelal een papieren representatie van die bron, tegenwoordig is daar de digitale Internet representatie bijgekomen. In de juriconnect identificatie zie je daar naar mijn idee ook het voorbeeld waarbij de representatie in zowel een papieren als digitale vorm kan worden uitgedrukt (isbn- en uri-verwijzing).

**Comment by FinnTiebout** [comment]
@kad-stapr juist relaties tussen concepten naar andere thesauri voegen toch informatie toe? 
Je hebt geen invloed op de kwaliteit van de andere thesauri waar je naar verwijst, dat risico herken ik. 
Doel je op het volgende scenario?: Vandaag is een relatie naar een concept in een andere thesauri terecht is, mogelijk wijzigt het concept morgen waardoor de verwijzing dan niet meer correct is. Het is waarschijnlijk dat je niet wordt geïnformeerd over die wijziging, waardoor er nu een onjuiste relatie in je thesauri aanwezig is. 
Ik zie het beheer van deze relaties voornamelijk als een operationele taak welke je moet beleggen binnen een thesauri beheer team.

**Comment by kad-stapr** [comment]
@FinnTiebout wat ik al aangaf is het voor mij nog een vraag en kan ik mij situaties voorstellen waarbij het zinvol is om die relaties tussen concepten te leggen. Je schetst inderdaad een scenario waarin verwijzingen in de loop van de tijd niet meer hetzelfde zijn en dat dit niet opgemerkt wordt, en daarom de vraag welke usecases we wel/niet willen ondersteunen. Het onderhouden van die relaties is denk ik een belangrijk issue, en hoe meer relaties er zijn hoe meer onderhoud er nodig zal zijn en wat (denk ik) lastig is om in te regelen. 
Wellicht is het een optie (wordt dit wellicht al bedoeld??) om te streven waarin een concept onderdeel is van meerdere thesauri, uitgaande van de veronderstelling dat een thesaurus een specifiek domein/doel dient en er op die betreffende thesaurus ook gericht onderhoud plaats vindt. In deze veronderstelling worden concepten in een conceptschema onderhouden, en dit schema is niet noodzakelijkerwijs ook een thesaurus specificatie..... Maar wellicht zijn hier andere ideeën over?

**Comment by GeraldGrootRoessink** [comment]
> Gebruik daarbij indien beschikbaar de uri van de bron
Ik stel voor een een afspraak maken om de URI te combineren met de titel/label, bijvoorbeeld: [title](https://www.example.com)

**Comment by GeraldGrootRoessink** [comment]
@kad-stapr 
>  concept onderdeel is van meerdere thesauri

Concepten spelen een rol in de besluitvorming bijvoorbeeld bij het bepalen van studiefinanciering. Ze mogen niet zonder medeweten van de beslisser een andere definitie krijgen.

**Comment by FinnTiebout** [comment]
conclusie:
Opsplitsen.
3 en 4 combineren en nieuw issue voor opvoeren, dit gaat over dct:source en bronverwijzingen. 
1 nieuw issue voor aanmaken, hoe gaan we verwijzen andere domeinen en hoe nemen we de hierarchie binnen die domeinen hierin mee.
2 hier is overeenstemming over.
