### ISSUE TITLE
Splitsen document in stuk over (stelsel)catalogi en het stuk over begripsbeschrijvingen

### ISSUE THREAD

**Issue by architolk** [pldn/nederlands-profiel-voor-stelselcatalogi#50]
We hebben in het stuk de ambitie om uiteindelijk uit te komen op een profiel waarmee je een volledige (stelsel)catalogi kunt beschrijven. Een begripsbeschrijving is daar slechts een onderdeel van. Eigenlijk hebben we nu vooral dit stuk uitgewerkt.

Afgesproken is om het document te splitsen: (a) een profiel voor begripsbeschrijvingen en (b) een overkoepelend document waarin we ingaan op (stelsel)catalogi en welke onderdelen daarin worden beschreven (waarbij we dan al 1 onderdeel hebben beschreven en de anderen nog moeten doen - of verwijzen naar andere standaarden waar dit al is gebeurd, zoals MIM)

**Comment by Bakkej** [comment]
Huidige standaard gaat volledig over Begripsbeschrijvingen.
