### ISSUE TITLE
Opdeling van het document die beter aansluit bij normatieve / niet-normatieve deel

### ISSUE THREAD

**Issue by architolk** [pldn/nederlands-profiel-voor-stelselcatalogi#51]
Afgesproken dat we het document als volgt opdelen:
- Overzicht van wat verplicht/aanbevolen/optioneel
- Uitleg van alle elementen (los van de taalbinding)
- Best practices van specifieke onderwerpen (zoals: labels, hergebruik/harmonisatie, etc)
- Taalbinding naar SKOS/DCT

**Comment by Bakkej** [comment]
Voldoende verwerkt
