### ISSUE TITLE
URI's van het profiel aanpassen

### ISSUE THREAD

**Issue by RiX012** [pldn/nederlands-profiel-voor-stelselcatalogi#52]
Nu zijn de URI's gesteld op http://pldn.nl/nederlands-profiel-voor-stelselcatalogi/id/concept/*.

Wellicht kunnen we dit door gebruik van w3id.org wat permanenter/leesbaarder/korter maken?

Zoiets als: w3id.org/id/nl-profiel-sc/*

**Comment by ArjenSantema** [comment]
Zie issue 41
