### ISSUE TITLE
Naamgevingsconventies

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [pldn/nederlands-profiel-voor-stelselcatalogi#53]
Het profiel heeft nodig geen naamgevingsconventiesom interoperabiliteit te vergroten.

ISO 25964 heeft er wel een flink aantal in het Engels.
Dit is wat ik er uit heb gevist en vertaald naar het Nederlands

![image](https://user-images.githubusercontent.com/20146034/202650599-cc16669b-9c74-4175-b1ad-cad15991fbaa.png)

Mijn voostel is om zoiets onderdeel te maken van het profiel.
Gerald

**Comment by RiX012** [comment]
Dit zou wat mij betreft inderdaad een Best Practice moeten zijn

**Comment by Bakkej** [comment]
Arjen gaat dit verder verwerken

**Comment by ArjenSantema** [comment]
Opgenomen in het hoofdstuk Best practices.
