### ISSUE TITLE
skos:inScheme -> "behoort tot" of iets anders?

### ISSUE THREAD

**Issue by Bakkej** [pldn/nederlands-profiel-voor-stelselcatalogi#58]
We hebben skos:inScheme vertaald naar "behoort tot", maar wat bedoelen we daar eigenlijk mee?
@hoverbee heeft hier een opmerking over gemaakt via hypothesis. 
> Volgens ons ook. Maar dan klopt onze definitie niet. Het is niet "Relateert een begrip tot het begrippenkader waartoe het behoort" maar "Relateert een begrip tot een begrippenkader". Dus _een_ begrippenkader en niet _het_ en een begrip behoort niet tot een begrippenkader. Het bestaat 'an sich' en kan in een begrippenkader worden opgenomen.

Dit is in principe correct, maar hoe willen we hier mee omgaan? 
Als we "behoort tot" uit de definitie schrappen, dan moeten we ook een andere voorkeursterm kiezen.

**Comment by hoverbee** [comment]
Als we skos:ConceptScheme '_begrippenkader_' noemen, laten we dan skos:inScheme '_in kader_' noemen.

**Comment by RiX012** [comment]
> Als we skos:ConceptScheme '_begrippenkader_' noemen, laten we dan skos:inScheme '_in kader_' noemen.

Hiermee impliceren we dan ook wel dat wat wij Begrippenkader noemen, 'internationaal' gelijk staat aan thesaurus. Dit is namelijk hoe in het SKOS <> ISO25964 samenspel als best practice wordt geadviseerd om skos:ConceptScheme en 'Thesaurus' gelijk te stellen.

**Comment by Bakkej** [comment]
in kader wordt doorgevoerd
