### ISSUE TITLE
Use Case opsomming klopt niet

### ISSUE THREAD

**Issue by adgerrits** [pldn/nederlands-profiel-voor-stelselcatalogi#59]
Het 4e onderdeel van de opsomming in paragraaf [1.4 Use Cases](https://pldn.github.io/nederlands-profiel-voor-stelselcatalogi/#use-cases) is niet goed geformuleerd. De eerste drie aanduidingen (Begrippenlijst, Taxonomie en Thesaurus) zijn helder maar "Nadere typering van begrippen en relaties (could have)" klopt niet. De toevoeging '(could have)' lijkt er op te wijzen dat het eerder werd beschouwd als onderdeel van 3. Thesaurus. Het daar terug zetten zou ik logisch vinden. 
Bij 4. zou ik eerder 'Ontologie' verwachten, maar gelet op mijn beperkte materiekennis is er vast een goede reden dat dat er niet staat...

**Comment by ArjenSantema** [comment]
4e onderdeel helemaal weggehaald bij uses cases en opgenomen in de paragraaf uitbreidingen.
