### ISSUE TITLE
Begrippen opnemen in LD store tbv dereferencing

### ISSUE THREAD

**Issue by ArjenSantema** [pldn/nederlands-profiel-voor-stelselcatalogi#61]

**Comment by architolk** [comment]
Als Geonovum het beheer gaat voeren, dan kan dit vermoedelijk via BegrippenXL, aangezien zij dit nu ook al doen voor enkele begrippenkaders, zie bv https://definities.geostandaarden.nl/imkl2015/nl/

**Comment by ArjenSantema** [comment]
De begrippen zijn opgeomen in https://begrippen.geostandaarden.nl/stelsel/nl/. Dit is niet de formele productieomgeving want de standaard is nog niet formeel in beheer en het is ook niet zeker of het beheer bij Geonovum wordt belegd, Logius is ook een potentiële kandidaat.
De dereferencing werkt nog niet goed.

**Comment by ArjenSantema** [comment]
De dereferencing werkt inmiddels goed.
