### ISSUE TITLE
Uitwerken verwijzen naar begrippen en termen in tekst

### ISSUE THREAD

**Issue by Bakkej** [pldn/nederlands-profiel-voor-stelselcatalogi#66]
@architolk 

Uitwerken gebruik <<>> en "".

Mogelijk opnemen als bestpractice.

**Comment by ArjenSantema** [comment]
**Voorstel tekstje**:
Als een term uit meerdere woorden bestaat ontstaan grammaticaal onlogische zinnen, zoals "Heeft bovenliggend begrip relateert een begrip aan...". Dan is het nodig om aan te duiden dat *heeft bovenliggend begrip* 1 begrip aanduidt. Semantisch gezien is het gebruik van enkele of dubbele aanhalingstekens dan onjuist. Daarmee wordt verwezen naar een term en niet naar het begrip. Dit wordt duidelijk in een zin als "De term  'bank' kan zowel een financiële instelling als een zitmeubel aanduiden". In de voorliggende standaard is het essentieel dat duidelijk is wanneer het over een term gaat en wanneer over een begrip. Dit onderscheid is bekend als de [use-mention distinction](https://en.wikipedia.org/wiki/Use%E2%80%93mention_distinction). Voor het aanduiden van een begrip is geen duidelijke standaard. Hier gebruiken we <<...>> om waar nodig aan te geven dat het om een begrip gaat. Bijvoorbeeld "<<Heeft bovenliggend begrip>> relateert een begrip aan...".

**Comment by architolk** [comment]
Voorstel zou zijn om « en » te gebruiken (ALT-174 en ALT-175 op Windows, OPTION-\ en OPTION-SHIFT-\ op een Mac): guillements, "french quotation marks"

**Comment by ArjenSantema** [comment]
Tekst aangepast met waar nodig « en »
