### ISSUE TITLE
Metagegevens

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [pldn/nederlands-profiel-voor-stelselcatalogi#68]
Een subgroep heeft gewerkt aan de metagegevens van een begrippenkader. Bijvoorbeeld, wie heeft het gemaakt, wannneer enzovoorts. Dit werk is gebaseerd op DCAT en ADMS. In de werkgroep is geconstateerd dat dit algemener  dan de Nederlandse standaard voor het beschrijven van begrippen. Deze metagegevens zien we bijvoorbeeld ook bij een ontologie.  Om die reden is besloten om dit werk niet op te nemen in deze standaard maar uit te zien naar een aparte standaardisatie-activiteit ten dienste van het (federatieve) datastelsel van den overheid. 

Het issue:  deze ontwerpbeslissing en de verwachting dat het nog komt, is nergens vermeld.

**Comment by hoverbee** [comment]
Misschien goed bij de community voor DCAT-AP-NL onder de aandacht te brengen dat begrippenkaders een interessante categorie zijn die mogelijk specifieke aanwijzingen kunnen gebruiken voor de omgang met bepaalde metadata-eigenschappen.  @CasperKoop is dat iets wat jij daar kunt brengen?

**Comment by CasperKoop** [comment]
Ja, goed idee @hoverbee .
@ArjenSantema , jij zou na de laatste sessie nog het een en ander uitwerken, is dat de laatste versie die in [deze map](https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/tree/main/sessies/metadata) staat?

**Comment by ArjenSantema** [comment]
De inhoud van de Excel had ik al wel omgezet naar ttl. Deze vind je op https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/blob/main/respec/stelselcatalogus/thesaurus.ttl.  Dit is een begin. Definities en scope notes moeten nog worden toegevoegd.

**Comment by Bakkej** [comment]
Wordt verder opgepakt als onderdeel van issue #64
