### ISSUE TITLE
Presentatie van het begrippenkader op Geonovum verbeteren

### ISSUE THREAD

**Issue by JosVanderArend** [pldn/nederlands-profiel-voor-stelselcatalogi#70]
Bij begrippen staat de code van een begrip in de voorkeursterm geïntegreerd, zie bijvoorbeeld "CC Code" (links) en "CCCode" (rechts) in https://begrippen.geostandaarden.nl/stelsel/nl/page/Notation

**Comment by Bakkej** [comment]
Dit is inmiddels aangepast. had met configuratie te maken.
