### ISSUE TITLE
Wijzigingsvoorstel 'naam' i.p.v. 'label' bij begrippenkader, collectie en brondocument 

### ISSUE THREAD

**Issue by fzand** [pldn/nederlands-profiel-voor-stelselcatalogi#72]
Begrippenkader, collectie en brondocument kennen nu een conceptueel element genaamd 'label', vermoedelijk gebaseerd op de overeenkomstige eigenschap rdfs:label.

In de te ontwikkelen online begrippenkader-editor lijkt 'label' echter geen handige term voor niet-technische gebruikers.

Om de online begrippenkader-editor toegankelijker te maken voor niet-technische gebruikers, wordt voorgesteld om in GUI van de editor de term 'naam' te gaan gebruiken in plaats van 'label'.

Dit wijzigingsvoorstel houdt in dat ook in de standaard de term 'naam' gebruikt wordt, wat in lijn lijkt te zijn met de algemene naamgevingsconventie die wordt toegepast op de andere conceptuele elementen.

**Comment by RiX012** [comment]
Persoonlijk voel ik meer voor 'label'. Maar ik kan vanwege de argumentatie en de impact prima meegaan in het voorstel.

**Comment by pmaria** [comment]
+1 voor naam in de conceptuele beschrijving

**Comment by hoverbee** [comment]
+1 voor naam in de conceptuele beschrijving

**Comment by architolk** [comment]
Ik vind "naam" ook beter voor begrippenkader, brondocument en collectie. Met dan wel de (huidige) taalbinding naar rdfs:label. Bij brondocument kan ik me voorstel om (ook) "titel" op te nemen, met als taalbinding dct:title

**Comment by ArjenSantema** [comment]
verwerkt
