### ISSUE TITLE
Taalbinding van Brondocument en url

### ISSUE THREAD

**Issue by fzand** [pldn/nederlands-profiel-voor-stelselcatalogi#74]
De taalbinding van Brondocument en url is volgens mij ongelukkig.

Hieronder heb ik VOWL misbruikt omdat te visualiseren:

![image](https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/assets/11835251/2b069cda-d90e-4ef0-9c58-bec0a26eed53)

De domein en range in van foaf: page is echter als volgt:

![image](https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/assets/11835251/919b5706-4be1-4b96-bd52-7076d4e6d057)

Hieronder enkele alternatieve taalbindingen:

![image](https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/assets/11835251/b5b5d93e-f160-47d2-a746-f5caaa81cca8)

**Comment by Bakkej** [comment]
Ik zie dat we het beoogd gebruik inderdaad beter kunnen beschrijven. De analyse waarna gekozen is voor foaf:page staat hier: https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/blob/main/sessies/bronverwijzing/Bronverwijzing.md

Hierin is o.a. schema:url ook bekeken, maar niet voor gekozen. 

<<url>> willen we gebruiken om naar de vindplaats van het document op het web te verwijzen. Want dit is niet noodzakelijkerwijs de URI van het document (als we al uit gaan van een linked data implementatie). 

Er zijn destijds geen betere alternatieve eigenschappen gevonden. Als we kijken naar DCAT introduceren ze daar dcat:accessURL. Dat is eigenlijk wat we willen, maar dat past dan weer niet goed op foaf:Document. 

Na wat zoeken heb ik [hasURL](http://purl.org/spar/fabio/hasURL) gevonden in de SPAR ontologies. Dit is een datatype property die als waarde een xsd:anyURI verwacht. Dit lijkt goed te passen, misschien kunnen we daar voor kiezen.
Definitie: _An identifier, in form of an HTTP Universal Resource Locator (URL), for a particular resource on the World Wide Web._

**Comment by pmaria** [comment]
Een reden om destijds te kiezen voor `foaf:Document` en `foaf:page` was om het simpel te houden en om te voorkomen dat we een wirwar van vocabulaires moesten gebruiken, met de daarbij komende semantische commitment. 

[hasURL](http://purl.org/spar/fabio/hasURL) maakt bijvoorbeeld weer verbinding met FRBR  wat de nodige complexiteit met zich meebrengt.

In mijn optiek dekt `foaf:page` prima de lading in dit geval.

**Comment by RiX012** [comment]
> Een reden om destijds te kiezen voor `foaf:Document` en `foaf:page` was om het simpel te houden en om te voorkomen dat we een wirwar van vocabulaires moesten gebruiken, met de daarbij komende semantische commitment.
> 
> [hasURL](http://purl.org/spar/fabio/hasURL) maakt bijvoorbeeld weer verbinding met FRBR wat de nodige complexiteit met zich meebrengt.
> 
> In mijn optiek dekt `foaf:page` prima de lading in dit geval.

Dit onderschrijf ik. Ondanks dat er betere opties zijn, is de afweging om zo zuinig mogelijk om te gaan met gebruik van externe ontologieën ook wat waard.

**Comment by hoverbee** [comment]
+1 voor simpel houden. Als je moeilijker nodig hebt kun je afwijken van het profiel.

**Comment by fzand** [comment]
Het was niet mijn bedoeling om het complexer te maken, maar om te wijzen op een verkeerd gebruik van foaf:page en foaf:Document. De range van foaf:page is volgens de documentatie foaf:document en niet het domein. 

In het DSO/STOP (en in de toekomst wellicht voor alle overheidspublicaties) speelt FRBR een belangrijke rol bij het verwijzen naar wet-regelgeving. Ook voor het nieuwe model voor de Stelselcatalogus willen kijken hoe we bij dat gebruik kunnen aansluiten. Ik ben dan ook zeer gecharmeerd door de - door Jesse - aangedragen hasURL.

Hoewel ik nier direct zie dat het vervangen van een (extern) klasse en een proportie door een andere de taalbinding nu zoveel moeilijker maakt, wordt het hogere doel (semantische interoperabiliteit van overheidsinformatie) wel gediend.

**Comment by RiX012** [comment]
> Het was niet mijn bedoeling om het complexer te maken, maar om te wijzen op een verkeerd gebruik van foaf:page en foaf:Document. De range van foaf:page is volgens de documentatie foaf:document en niet het domein.

Hier ben ik onlangs ook tegenaan gelopen bij het veranderen van het schema voor onze thesaurus. Op zich mag het wel hoe het er nu staat. Maar indirect declareer je natuurlijk ook dat de waarde van de URL een `foaf:Document` is. De vraag is of we dat bedoelen. 

Gebruik maken van `hasURL` vind ik prima. Als we kunnen overzien welke SPAR zaken er dan nog meer bijkomen. Overigens maken wij intern ook veel gebruik van de SPAR ontologies, dus die stap zou ik niet erg vinden.

**Comment by architolk** [comment]
Ik ben nog steeds voor het gebruik van dct:bibliographicCitation :-) (wat ook de mogelijkheid biedt om ISBN nummers enzo hier in te stoppen. Een URI zou dan overigens wel een xs:anyURI zijn -> want een literal. Dat past voor mijn gevoel met wat we willen bereiken: een verwijzing naar de vindplaats van het daadwerkelijke ding (of dit nu op het internet is of niet).

Bovendien klopt m.i. sowieso de "harde" eis om foaf:Document te gebruiken niet met onze besprekingen, daarin werd juist voorgesteld om keuzevrijheid te houden hoe we de taalbinding van brondocument zouden plaatsen. Sommigen vinden foaf:Document handig, maar er zijn ook alternatieven die we hebben besproken en waarbij we m.i. geen harde keuze in wilden maken.

Alternatief:
- Gebruik foaf:Document als de URI van de resource gelijk is aan de URI van de vindplek. Dan klopt het
- Gebruik dct:BibliographicResource (of iets anders) als je een eigen ding in je begrippenkader opneemt, met dct:bibliographicCitation (of wellicht foaf:page, want je zou kunnen stellen dat dit dan weer wel kan) voor de URI of een andere verwijzing naar de vindplaats.

**Comment by pmaria** [comment]
@fzand schreef:
> Het was niet mijn bedoeling om het complexer te maken, maar om te wijzen op een verkeerd gebruik van foaf:page en foaf:Document. De range van foaf:page is volgens de documentatie foaf:document en niet het domein.

Ik zie in waarom dit verkeerd gebruik is.  De `range` van `foaf:page` is inderdaad foaf:Document. Het `domain` is open en dus kan `foaf:page` op alle resource gebruikt worden. Ook resources die zelf weer getypeerd zijn als `foaf:Document`.

Ik zie dit als een basispatroon die we minimaal willen ondersteunen met dit profiel.
Verder kan dit in toepassingen verder aangekleed worden, indien gewenst.


@architolk schreef:
> Ik ben nog steeds voor het gebruik van dct:bibliographicCitation :-) (wat ook de mogelijkheid biedt om ISBN nummers enzo hier in te stoppen. Een URI zou dan overigens wel een xs:anyURI zijn -> want een literal. Dat past voor mijn gevoel met wat we willen bereiken: een verwijzing naar de vindplaats van het daadwerkelijke ding (of dit nu op het internet is of niet).

Dit is al eerder wel besproken. Bibliographic citation is bedoeld voor een citeertitel. Dat is niet wat we hiermee uitproberen te drukken. De definitie van de url eigenschap luidt: "Een url is de vindplaats van een bron op het internet."

Een citeertitel mag ook opgenomen worden voor deze resource, maar daarvan hebben we besloten om deze niet onderdeel te maken van het standaardprofiel.

**Comment by architolk** [comment]
Ik zie 't. Ik vind op zich foaf:page dan op zich best prima als taalbinding voor nu. Wel belangrijk om foaf:Document niet te gebruiken.

**Comment by ArjenSantema** [comment]
specificatie is nu voldoende open dat je met beide smaken uit de voeten kunt.
