### ISSUE TITLE
de betreffende moet zijn het betreffende

### ISSUE THREAD

**Issue by hoverbee** [pldn/nederlands-profiel-voor-stelselcatalogi#77]
https://github.com/pldn/nederlands-profiel-voor-stelselcatalogi/blame/cac70ff54007a3209cc3754a12859771aee15633/respec/H2-conceptuele-beschrijving.md#L491
Er staat "Dit kenmerk relateert het begrip aan **de** betreffende [=brondocument=]."
"de" moet "het" zijn.

**Comment by Bakkej** [comment]
Dit is aangepast in het document.
