### ISSUE TITLE
Hoe verwerken we context in het model?

### ISSUE THREAD

**Issue by FinnTiebout** [pldn/nederlands-profiel-voor-stelselcatalogi#9]
Hoe leggen we context bij een begrip vast in het profiel voor de StelselCatalogus?

**Comment by lvdbrink** [comment]
Ik heb nog niet helemaal duidelijk wat er met context bedoeld wordt. In mijn ogen is het begrippenkader waarvan het begrip onderdeel is, de context.

**Comment by FinnTiebout** [comment]
Context is een aanvulling op de definitie (?), uit de definitie zou de context opgemaakt kunnen worden, maar deze is dan volgens mij enkel bruikbaar voor mensen, niet voor computers. 
Een begrippenkader (conceptScheme) is een mogelijke oplossing, ik twijfel of een begrip dan in meerdere begrippenkaders voor mag komen?
Denk aan het begrip Utrecht, kan deze zowel in het begrippenkader **steden** als **hoofdsteden** voorkomen?

**Comment by GeraldGrootRoessink** [comment]
Het lijkt me nuttig om de context/kader waarin een begrip wordt gebruikt te identificeren en te beschrijven met conceptScheme. Ik hik alleen wel aan tegen het voorbeeld Utrecht.  Dat ervaar ik meer als een ding dat in beeld komt als een instantie die van een klasse "Stad".  Ter vergelijking:  "Utrecht" komt toevallig voor in de dikke van Dale, maar "Zwolle" niet.  Wat is de regel?  "Stad" en "hoofdstad" zijn denk ik wel begrippen.

**Comment by pmaria** [comment]
+1 voor begrippenkader als representatie van context.

Eens met @GeraldGrootRoessink dat Utrecht een ongelukkig voorbeeld is. Hoewel het mogelijk is om instanties van steden e.d. te representeren als begrip is het meestal weinig nuttig.

**Comment by FinnTiebout** [comment]
Conclusie:

conceptScheme wordt gebruikt om context vast te leggen.
Vanuit functioneel oogpunt kunnen we zeggen dat het begrippenkader waar het begrip onderdeel van is de context bepaald.

**Comment by FinnTiebout** [comment]
context verwerken we door gebruiken te maken van conceptschema.
